### ISSUE TITLE
problem adding mob eggs

### ISSUE THREAD

**Issue by frizzbee30** [kangarko/CoreArena#10]
Hi, since (I think) the latest update, it doesn't seem to be taking mythic mob eggs? Trying to add an egg is refused and then seems to 'lock' the interface to adding any other vanilla mobs for the arena?

Obviously there was the code change for the new way mob eggs are handled etc

Thanks

More Information: 
Could not detect monster type from ItemStack{MONSTER_EGG x 1, SPAWN_EGG_META:{meta-type=SPAWN_EGG, display-name=Spawn Hostile Snowman, lore=[A Mythical Egg that can, be used to resurrect a, hostile_snowman], enchants={DURABILITY=10}}}
iReport / Could not detect monster type from ItemStack{MONSTER_EGG x 1, SPAWN_EGG_META:{meta-type=SPAWN_EGG, display-name=Spawn Hostile Snowman, lore=[A Mythical Egg that can, be used to resurrect a, hostile_snowman], enchants={DURABILITY=10}}}
	 at me.kangarko.corearena.nul.w.const(SourceFile:13)
	 at me.kangarko.corearena.nul.bn.const(SourceFile:41)
	 at me.kangarko.corearena.nul.lPT7.const(SourceFile:74)
	 at me.kangarko.corearena.nul.coM9$super$1.const(SourceFile:180)
	 at me.kangarko.corearena.nul.coM9$super$1.const(SourceFile:177)
	 at me.kangarko.corearena.nul.c.const(SourceFile:870)
	 at me.kangarko.corearena.nul.coM9$super.const(SourceFile:177)
	 at me.kangarko.corearena.nul.bG.onInvClose(SourceFile:30)
	 at sun.reflect.GeneratedMethodAccessor348.invoke(Unknown Source)
	 at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	 at java.lang.reflect.Method.invoke(Unknown Source)
	 at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
	 at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
	 at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499)
	 at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484)
	 at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.handleInventoryCloseEvent(CraftEventFactory.java:886)

**Comment by kangarko** [comment]
Hey,

please try the absolute latest version & set Setup.Accept_Unsafe_Monster_Eggs to true :)

**Comment by frizzbee30** [comment]
Thanks  :)
