### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by LogGits** [kangarko/CoreArena#106]
```
00:51:33[GriefPrevention] _Redacted_ placed a sign @ world2: x7440, z11726;1;b1 ;Sand
ERROR 16/07/2018 00:51:33
00:51:33Could not pass event SignChangeEvent to CoreArena v1.6.10
Console 16/07/2018 00:51:33
00:51:33org.bukkit.event.EventException: null
at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.12.2.jar:git-Paper-1500]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-1500]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1500]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:527) ~[patched_1.12.2.jar:git-Paper-1500]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:512) ~[patched_1.12.2.jar:git-Paper-1500]
at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:2228) ~[patched_1.12.2.jar:git-Paper-1500]
at net.minecraft.server.v1_12_R1.PacketPlayInUpdateSign.a(SourceFile:44) ~[patched_1.12.2.jar:git-Paper-1500]
at net.minecraft.server.v1_12_R1.PacketPlayInUpdateSign.a(SourceFile:10) ~[patched_1.12.2.jar:git-Paper-1500]
at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Paper-1500]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_161]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_161]
at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [patched_1.12.2.jar:git-Paper-1500]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:849) [patched_1.12.2.jar:git-Paper-1500]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427) [patched_1.12.2.jar:git-Paper-1500]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:773) [patched_1.12.2.jar:git-Paper-1500]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1500]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
Caused by: java.lang.ClassCastException: org.bukkit.craftbukkit.v1_12_R1.block.CraftBlockState cannot be cast to org.bukkit.block.Sign
at me.kangarko.corearena.nul. .lpT8.onSignChange(SourceFile:72) ~[CoreArena-1.6.10.jar:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor631.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1500]
... 16 more
```

CoreArena build 1.6.10. Paperspigot 1500 1.12.2. Plugins: Griefprevention, GameAPI, CoreArena, ChatControl, AAC, a few others can provide in pm's if needed.

**Comment by kangarko** [comment]
Weird, but it seems that the event was fired even though no sign was really edited. I silenced this to the next release of CA and Puncher.
