### ISSUE TITLE
Error on startup.

### ISSUE THREAD

**Issue by LogGits** [kangarko/CoreArena#11]
Getting this error on startup. Latest version of CoreArena and Paperspigot.
```
10:46:15 at me.kangarko.corearena.nul.Lpt2.native(SourceFile:40)
at me.kangarko.corearena.nul.bA.case(SourceFile:29)
at me.kangarko.corearena.nul.Lpt2.<init>(SourceFile:29)
at me.kangarko.corearena.nul.cOM7.<init>(SourceFile:51)
at me.kangarko.corearena.nul.cOm1.const(SourceFile:41)
at me.kangarko.corearena.nul.super.throw(SourceFile:184)
at me.kangarko.corearena.nul.super.protected(SourceFile:144)
at me.kangarko.corearena.nul.aN.onEnable(SourceFile:103)
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316)
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404)
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:382)
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:331)
_ _ _ 
| | | | ___ ___ _ __ ___| |
| |_| |/ _ \ / _ \| '_ \/ __| |
| _ | (_) | (_) | |_) \__ \_|
|_| |_|\___/ \___/| .__/|___(_)
|_| 
!-----------------------------------------------------!
Error loading CoreArena v1.2.16, plugin is disabled!
Running on 1.12.1-R0.1-SNAPSHOT (v1_12_R1) & Java 1.8.0_91
!-----------------------------------------------------!
Error: Unable to get the error message, search above.
!-----------------------------------------------------!
[CoreArena] Disabling CoreArena v1.2.16
```

**Comment by LogGits** [comment]
Issue started on update 1.2.15. The plugin doesn't load.

**Comment by kangarko** [comment]
Hey, please test on 1.2.17 just released :)

**Comment by LogGits** [comment]
its this now
```
23:40:02 at me.kangarko.corearena.goto.nul.\\.LpT5.int(SourceFile:40)
at me.kangarko.corearena.goto.nul.\\.aK.IIllIIlIlIIIllIlIlIlllllIllIlllllllllIIIlIIIIlIlllllIIIllIllIlIIIllIIIlIIIllIIlIIIlllIIIlIlIllllIlIlIlIIlIIlIIlllIIlIIIIIllIllllIIIlIlIllllIIlllIllIIIlllIIIIIIlIIIIlIIlIlIIIlIllIllIIIIIIIllllIlIlIIlllllllIlIIllIlIlIlIllllllIlIllIIlIlIlllIlllllIlllIlIlIllllllIIlIllllIllIlIlIIIIlIllIllllIllllIlllIIIllIIIllllIIlIIIIlIllllIllllIIlIIlllIIllllllllIIlIIllIlIIlIlIIlIIIIllIIIIlIllIIIlIIllIllIIIllIllllllIIIIlIllllIllIlIlIllIlllIlIlIlIllIIlIIIlllllIllIIIlllllIlIllIllIlIIlIllIIIlIIIllllIIIIIlIIllllIlIlIlllI(SourceFile:29)
at me.kangarko.corearena.goto.nul.\\.LpT5.<init>(SourceFile:29)
at me.kangarko.corearena.goto.nul.\\.lPT8.<init>(SourceFile:51)
at me.kangarko.corearena.goto.nul.\\.cOm9.nul(SourceFile:41)
at me.kangarko.corearena.goto.nul.\\.AUX.lIIIIIIlIlIlllllIIIlIIIIIIIllIIIIIIIIlllIlllllIllllllIIlIlIIIIlIllIIlIlIIIlIIlllllIlIlllIIllIlIlllIlIIlIIlIllIlIIIIllIIIlIIIIIIllIlIlIIlllIlIllIIIIIIlIIIIllIlllIIIIIlIllllIIlllllllIllIIIIIllIIlIlllllIIllllIIIlllIlllIIIllIIlllllIIIlllllIIIllIlIlIIlIIllIIlIlIlllllIIlIIllIlllIlIIllIllIIIIIIIllIIllllIIIIIIIIIIlIlllIIIlIIIlllIIIllIIllIlIIlIIlIIlIIlIlIlIIIlIIIIIlllllllIlIIllIIIIIIIllIllllIlIlIlIIIIIIIIlIIlllIIllllllIIlllIllIlIIIlIlIllllIlIlIlIIlIlllllIlllIllIIlIllIlIllllIllIIIlIIlIlllllllIlIIlIIIIIIII(SourceFile:191)
at me.kangarko.corearena.goto.nul.\\.AUX.IlIlIlllIIllIlIlIlIlIllIIIIIlIlllIlIIlllIlIIIIIllllIIlIIIIIIIllllllIIIlIlIllIlIllllllllIlIllllIlIIIlIIIlllIIlIlIlIIlllllIlllIlllIIllIllIIIlllllIIIlIlIllIllIIlIlllIlIIIllIllIllIllllIIIllIIlIlllllllIIIlIllllIllIlIlIIIllllIlllIllIlllIlIIlIlllIlllIIIIIIlIlIlIlIlIlllllIIlIllllllIIlIlllIlIlIllIllIlIIlIlIIlIIllIlIIlllIIlIIlllllIlIlIllIIlIllllIlllIIIIIllIlIlIllllIIlIllIIlIIIllIIlIlIlIlIlllIllllllIIIllllllIIIIIlIIIIIlIlIIlIllIIIIllIlIIllIIIIlIlIIlIllIIllIlIlIllllIIIIIllIlllIIIIlIIlllIllIlIllIIlllllIlllII(SourceFile:151)
at me.kangarko.corearena.goto.nul.\\.X.onEnable(SourceFile:103)
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316)
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404)
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:382)
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:331)
_ _ _ 
| | | | ___ ___ _ __ ___| |
| |_| |/ _ \ / _ \| '_ \/ __| |
| _ | (_) | (_) | |_) \__ \_|
|_| |_|\___/ \___/| .__/|___(_)
|_| 
!-----------------------------------------------------!
Error loading CoreArena v1.2.17, plugin is disabled!
Running on 1.12.1-R0.1-SNAPSHOT (v1_12_R1) & Java 1.8.0_91
!-----------------------------------------------------!
Error: Unable to get the error message, search above.
!-----------------------------------------------------!
[CoreArena] Disabling CoreArena v1.2.17
```

**Comment by LogGits** [comment]
however, on my local computer it runs fine.

**Comment by kangarko** [comment]
Please PM me on SpigotMc with the error.log file.
