### ISSUE TITLE
Unable to join arena

### ISSUE THREAD

**Issue by TheWranger** [kangarko/CoreArena#122]
Upon updating to the latest CoreArena and GameAPI, whenever I try to join my arena, the arena immediately ends.
Console error:
```
16.08 05:57:35 [Server] INFO » CoreArena 1.7.1 encountered a NoSuchMethodError! Please check your error.log and report this issue with the information in that file.
16.08 05:57:35 [Server] INFO java.lang.NoSuchMethodError: me.kangarko.gameapi.ArenaClass.mayObtain(Lorg/bukkit/entity/Player;)Z
16.08 05:57:35 [Server] INFO at me.kangarko.corearena.nul. .Lpt9.nul(SourceFile:50)
16.08 05:57:35 [Server] INFO at me.kangarko.corearena.nul. .cON.nul(SourceFile:48)
16.08 05:57:35 [Server] INFO at me.kangarko.corearena.nul. .bO.int(SourceFile:88)
16.08 05:57:35 [Server] INFO at me.kangarko.corearena.nul. .bO.lIlIIlllIlllIllllIIlllllIllllIllIIIllIIllIlIIIIIlllIIlIllllIIIIllIlllllIlIllllIIIIllIlllIllIIlIIllllllllIIlllllIlllIIIlIIlllllIlIIIIIlllIllIIlIIlIllIlIIIIlIIIlIIllIIIlllIIlIIIlIIIIlIIllllIllIIllIllIlIIlIIlIlIllIllllllIIlIIIlllIIlIllIIlIIIIIIIIlIIIlIIllIlllIlIllIlIlIlIlIlIIIIlIlIllIllIIIIlllllllllIlIIlIlIIlIllIlllllIIlIIlIIllllIlllIIllIlllIlIlIlIlIIlIlIlllIlIllIlIlllIIIlIlIlIllIllIIlllIIllllIIllllllIlIIllIlllIIllIIllllllllllIIlllIllllllIlllIlIllIIIIllIlllllIIlllIllIlllllIllIllIlIllllllIllIllllIIl(SourceFile:71)
16.08 05:57:35 [Server] INFO at me.kangarko.corearena.nul. .at.nul(SourceFile:21)
16.08 05:57:35 [Server] INFO at me.kangarko.corearena.nul. .bO.nul(SourceFile:141)
16.08 05:57:35 [Server] INFO at me.kangarko.corearena.nul. .bO.nul(SourceFile:137)
16.08 05:57:35 [Server] INFO at me.kangarko.corearena.nul. .lPt7.nul(SourceFile:83)
16.08 05:57:35 [Server] INFO at me.kangarko.corearena.nul. .cOm1.int(SourceFile:253)
16.08 05:57:35 [Server] INFO at me.kangarko.corearena.nul. .cOm1.joinPlayer(SourceFile:153)
16.08 05:57:35 [Server] INFO at me.kangarko.corearena.nul. .lPT4.handleSubCommand(SourceFile:40)
16.08 05:57:35 [Server] INFO at me.kangarko.corearena.kautils.command.Lpt5.handleCommand(SourceFile:172)
16.08 05:57:35 [Server] INFO at me.kangarko.corearena.kautils.command.BaseCommand.onCommand(SourceFile:59)
16.08 05:57:35 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
16.08 05:57:35 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151)
16.08 05:57:35 [Server] INFO » *-----------------------------------------------*
16.08 05:57:35 [Server] INFO »  Error while joining TheWranger to DAF
16.08 05:57:35 [Server] INFO »  Arena has been stopped for safety.
16.08 05:57:35 [Server] INFO »  NoSuchMethodError: me.kangarko.gameapi.ArenaClass.mayObtain(Lorg/bukkit/entity/Player;)Z
16.08 05:57:35 [Server] INFO » *-----------------------------------------------*
16.08 05:57:35 [Server] INFO » The mob arena has finished.
```
error.log error:
```
------------------------------------[ 16.08.2018 05:57:35 ]-----------------------------------
CoreArena 1.7.1 encountered a NoSuchMethodError
Running Paper 1.12.2-R0.1-SNAPSHOT and Java 1.8.0_171
Plugins: CleanroomGenerator v1.0.0, RWeb v1.0, WDLCompanion v1.1.4, antiraildupe v1.2, PlaceholderAPI v2.9.1, NametagEdit v4.2.0, PandaWire v1.0.4-SNAPSHOT, SuperTrailsPro vv1.0.3.1, BowParticles v1.7.7, Minator v7.0, PigmanAttention v1.0, Treasures v3.0-pre21.5, GameAPI v1.2.3, ElytraParticles v1.5.9, TreasuresAddon-RecentFind v1.0.1, Libs4Paper v1.0, ViaVersion v1.4.1, ViaBackwards v2.3.2-DEV, CoreProtect v2.14.4, LuckPerms v4.2.54, AntiBotDeluxe v9.2 - GALAXY, FastCraft v2.0.3, BlockQuest v2.0-pre1.1, ViaRewind-Legacy-Support v1.3.1, BileTools v2, BannerBoard v1.9.9, Votifier v2.3.7, ProtocolLib v4.4.0-SNAPSHOT-b390, Reflex v10.7-2, LibsDisguises v9.5.1-SNAPSHOT, NoCheatPlus v3.16.1-SNAPSHOT-sMD5NET-b1148, eZProtector v4.3.1, MVdWPlaceholderAPI v2.5.1, VotingPlugin v5.13.3, FastAsyncWorldEdit v18.07.10-9a8ec50-1153-20.3.3, Emotes v4.1.1, VoidGenerator v1.0, FishinRoulette v1.5, React v6.568, DeluxeMenus v1.10.5, BlocksHub v2.1.1, AlwaysOnline v6.1, FeatherBoard v4.9.0, LabyModAPI v1.1, ConditionalCommands v1.4, ServerListPlus v3.4.8, Vault v1.6.8, NoAfkFishing v2.3, MassiveCore v2.14.0, NoHopperCraft v1.0, ViaRewind v1.3.10, MassiveCombat v2.14.0, ClientStats v2.8.5, MarketPlace v1.7.0, SEARCH v1.7.6, ProtocolSupportPotions v2.6, ViaCheckConnection v1.2.5q-SNAPSHOT, PetMaster v1.8.2, AttributeHider v5.1.1, dynmap v2.6-beta-1-Dev201807082003, SayNoToMcLeaks v1.7, ShopGUIPlus v1.18.0, WorldEdit v6.1.8-SNAPSHOT;cd4729f, TryMe v5.5.1, AcidIsland v3.0.9.3, HeadDatabase v4.3.6, LiteBans v2.3, WildInspect v1.1.9, The Multiverse-Core Plugin, TradeMe v5.2.0.0, AdvancedOreGen v1.4.1, Hydra v1.4.8_1, ASkyBlock-IslandBorder v2.3.0, CMI v8.0.4.6, WorldGuard v6.2.1;84bc322, MythicMobs v4.3.2-SNAPSHOT, Duels v3.1.1, WDLCompanionASkyBlockSupport v0.0.2, CoreArena v1.7.1, WorldGuardExtraFlags v3.0.4, SelectionVisualizer v1.10.0.0, ChatControl v7.9.4, Cartographer v12.11, CraftBook v3.9-SNAPSHOT-jenkins-CraftBook-221, ChestShop v3.9.2 (build 86), Confiscate v1.8.4, ChestShopLimiter v1.5, CraftBookNMS v3.9-SNAPSHOT-1.12.2, ChestShopNotifier v1.2.1-SNAPSHOT (build #23)
----------------------------------------------------------------------------------------------

More Information: 
Error while joining TheWranger to DAF
Arena has been stopped for safety.
%error
NoSuchMethodError me.kangarko.gameapi.ArenaClass.mayObtain(Lorg/bukkit/entity/Player;)Z
	 at me.kangarko.corearena.nul. .Lpt9.nul(SourceFile:50)
	 at me.kangarko.corearena.nul. .cON.nul(SourceFile:48)
	 at me.kangarko.corearena.nul. .bO.int(SourceFile:88)
	 at me.kangarko.corearena.nul. .bO.lIlIIlllIlllIllllIIlllllIllllIllIIIllIIllIlIIIIIlllIIlIllllIIIIllIlllllIlIllllIIIIllIlllIllIIlIIllllllllIIlllllIlllIIIlIIlllllIlIIIIIlllIllIIlIIlIllIlIIIIlIIIlIIllIIIlllIIlIIIlIIIIlIIllllIllIIllIllIlIIlIIlIlIllIllllllIIlIIIlllIIlIllIIlIIIIIIIIlIIIlIIllIlllIlIllIlIlIlIlIlIIIIlIlIllIllIIIIlllllllllIlIIlIlIIlIllIlllllIIlIIlIIllllIlllIIllIlllIlIlIlIlIIlIlIlllIlIllIlIlllIIIlIlIlIllIllIIlllIIllllIIllllllIlIIllIlllIIllIIllllllllllIIlllIllllllIlllIlIllIIIIllIlllllIIlllIllIlllllIllIllIlIllllllIllIllllIIl(SourceFile:71)
	 at me.kangarko.corearena.nul. .at.nul(SourceFile:21)
	 at me.kangarko.corearena.nul. .bO.nul(SourceFile:141)
	 at me.kangarko.corearena.nul. .bO.nul(SourceFile:137)
	 at me.kangarko.corearena.nul. .lPt7.nul(SourceFile:83)
	 at me.kangarko.corearena.nul. .cOm1.int(SourceFile:253)
	 at me.kangarko.corearena.nul. .cOm1.joinPlayer(SourceFile:153)
	 at me.kangarko.corearena.nul. .lPT4.handleSubCommand(SourceFile:40)
	 at me.kangarko.corearena.kautils.command.Lpt5.handleCommand(SourceFile:172)
	 at me.kangarko.corearena.kautils.command.BaseCommand.onCommand(SourceFile:59)
	 at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
	 at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151)
	 at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:685)
----------------------------------------------------------------------------------------------
```
Running Minecraft 1.12.2 Paper 1516

**Comment by kangarko** [comment]
Please update to GameAPI 1.2.5 just released.
