### ISSUE TITLE
error

### ISSUE THREAD

**Issue by LogGits** [kangarko/CoreArena#144]
Right clicking the gold nugget for money. Using paperspigot 1.12.2 build 1587. Corearena 1.7.11 gameapi 1.3.0
```
FATAL 17/11/2018 22:32:39
22:32:39Error executing task
Console 17/11/2018 22:32:39
22:32:39java.util.concurrent.ExecutionException: java.lang.AssertionError: TRAP
at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_181]
at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_181]
at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:47) ~[patched_1.12.2.jar:git-Paper-1587]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850) ~[patched_1.12.2.jar:git-Paper-1587]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1587]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1587]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1587]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.AssertionError: TRAP
at net.minecraft.server.v1_12_R1.ItemStack.F(ItemStack.java:117) ~[patched_1.12.2.jar:git-Paper-1587]
at net.minecraft.server.v1_12_R1.ItemStack.setCount(ItemStack.java:888) ~[patched_1.12.2.jar:git-Paper-1587]
at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:441) ~[patched_1.12.2.jar:git-Paper-1587]
at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1050) ~[patched_1.12.2.jar:git-Paper-1587]
at net.minecraft.server.v1_12_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:26) ~[patched_1.12.2.jar:git-Paper-1587]
at net.minecraft.server.v1_12_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:5) ~[patched_1.12.2.jar:git-Paper-1587]
at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Paper-1587]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_181]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_181]
at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) ~[patched_1.12.2.jar:git-Paper-1587]
... 5 more
```

**Comment by kangarko** [comment]
Update your PaperSpigot, this is not caused by us.

**Comment by kangarko** [comment]
I tried to cancel the event in the next release, see if that helps
