### ISSUE TITLE
it's error .. is what??

### ISSUE THREAD

**Issue by Rirbe** [kangarko/CoreArena#160]
java.lang.ExceptionInInitializerError
[05:42:13 INFO]:        at me.kangarko.corearena.CoreArenaPlugin.IlllllllIlIllIIlllIIllllIIlIlIlllIlllllIIIIlIllllllIlIIllIllIIlllIIlIIllIlIIllIllllIlIIlIIIlIllIllIlIIIIllIIllIIIIllllIlllIlIllIlIlIIlIIlllIIllIllllIIllIIIIIIIIIIlllIIIlIllIIIIIIIIllIllIllIIIlIllIlIllIlIIIlIIIlIIlIIIlIlIllIlIIlIIIIIIIIIIIIIIllllIllIlIIIIIIlIIIIIlIIlIlllIlIIIllIIIIlIlIlIllIIIIlIIlllIIlIIIIIlIIllllIIIIlIIIllIIIIIllllllIlIllIIIlIlIIIllIllllIIlIIllIlIIllIIlIllllIlIIIIllIlllIIIlIIllIIIlIIIllIIlIIIllIlIIllIllIIlIIIIlIlllllllllIllIlIlIIlIIlllllIlIllIIIIIlIIlIllIlllIIlllIllIIIIIIIIlIllI(SourceFile:45)
[05:42:13 INFO]:        at me.kangarko.corearena.nul. .LPT8.llIllIllIIlllllllIlIIlIlIIIIIlIIlllIIlIlIIIllIIIlIIlIIlIlIlIlIllllIllIllIIlIlIIlIIlIIlllIIlIlllIlllllllIIlllIlllllllIllIIIIllIlIIIIIIlIllllIlIlllIlIlllIIIIlIllIllIlIIllIIllIlIlllIllIIIIlIlIlIIIIlllIlIllIllIlllIllIllIIIllIIllllIIIlllIllIIlIlllIlllIllIllIIllIIlllIlllIlIllIIlIIllIllllllIlIIlllIIllIIllIlIIIIIlllIIlllIIIlIIlllIlIIllllllllIIIIlIIlIllIlIllIlllIlIIlIlIlllIIllIlIllllIllIllIIlIIIIIlIIllIlllIIIIllllIllIIlIIIIIIlIIllIIIIllllIIIlIIIlIlllllIlIlIllIlIIllllllIllIIlIIIlIlIllllIIlIllIIIllIlllIlII(SourceFile:117)
[05:42:13 INFO]:        at me.kangarko.corearena.nul. .ai.IIlllIllllllIIIIIIlllllIIIlIIllIIlIIlIlIlIIlIllIIlIIIllIIIIllllIlllIlIllIllIlIIllllllllllIllIlIIlllIlIllIlIIIIIlIllllIlIIlllIlIIIlIlIlllllIIIlIlIIIIIIlIIIlIIllIlllIIlIllIlIlIIlllIIlllIIlIlIlllIlllllIllIIllllllIIIIllIlIllIlIIlIIlIlIlIlIIlIlIIIllllIlIlllllllllIIIlIlllIllIIIllIlIlIIIIlIllIIIIIlllllIIIlIlIIllllIllIlIIIIIIlllIIIlIlIIlIllIIllllIllIIlIIIIllIIIlIllIllllIllllIIlIllIlIIIIllIIIIllIIlIIIIIIIlIIIlIlIlllIllIIlIIlllllIlIllIlllIllIIIIIIlIIIlIlIlIllIlIIlIlllllllIlIllIlIIIIIIlIIllllIIllIIIIIlIIII(SourceFile:341)
[05:42:13 INFO]:        at me.kangarko.corearena.nul. .ai.a(SourceFile:330)
[05:42:13 INFO]:        at me.kangarko.corearena.nul. .a.nul(SourceFile:77)
[05:42:13 INFO]:        at me.kangarko.corearena.nul. .a.nul(SourceFile:73)
[05:42:13 INFO]:        at me.kangarko.corearena.nul. .interface$AUX.nul(SourceFile:118)
[05:42:13 INFO]:        at me.kangarko.corearena.nul. .interface.IlllllllIlIllIIlllIIllllIIlIlIlllIlllllIIIIlIllllllIlIIllIllIIlllIIlIIllIlIIllIllllIlIIlIIIlIllIllIlIIIIllIIllIIIIllllIlllIlIllIlIlIIlIIlllIIllIllllIIllIIIIIIIIIIlllIIIlIllIIIIIIIIllIllIllIIIlIllIlIllIlIIIlIIIlIIlIIIlIlIllIlIIlIIIIIIIIIIIIIIllllIllIlIIIIIIlIIIIIlIIlIlllIlIIIllIIIIlIlIlIllIIIIlIIlllIIlIIIIIlIIllllIIIIlIIIllIIIIIllllllIlIllIIIlIlIIIllIllllIIlIIllIlIIllIIlIllllIlIIIIllIlllIIIlIIllIIIlIIIllIIlIIIllIlIIllIllIIlIIIIlIlllllllllIllIlIlIIlIIlllllIlIllIIIIIlIIlIllIlllIIlllIllIIIIIIIIlIllI(SourceFile:56)
[05:42:13 INFO]:        at me.kangarko.corearena.nul. .interface.int(SourceFile:52)
[05:42:13 INFO]:        at me.kangarko.corearena.nul. .ai.onEnable(SourceFile:238)
[05:42:13 INFO]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254)
[05:42:13 INFO]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:325)
[05:42:13 INFO]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[05:42:13 INFO]:        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:441)
[05:42:13 INFO]:        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:355)
[05:42:13 INFO]:        at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:613)
[05:42:13 INFO]:        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:575)
[05:42:13 INFO]:        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:435)
[05:42:13 INFO]:        at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316)
[05:42:13 INFO]:        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:791)
[05:42:13 INFO]:        at java.lang.Thread.run(Unknown Source)
[05:42:13 INFO]: java.lang.NullPointerException
[05:42:13 INFO]:        at me.kangarko.corearena.nul. .COM4.nul(SourceFile:44)
[05:42:13 INFO]:        at me.kangarko.corearena.nul. .COM4.<init>(SourceFile:38)
[05:42:13 INFO]:        at me.kangarko.corearena.nul. .COM4.<clinit>(SourceFile:24)
[05:42:13 INFO]:        at me.kangarko.corearena.CoreArenaPlugin.IlllllllIlIllIIlllIIllllIIlIlIlllIlllllIIIIlIllllllIlIIllIllIIlllIIlIIllIlIIllIllllIlIIlIIIlIllIllIlIIIIllIIllIIIIllllIlllIlIllIlIlIIlIIlllIIllIllllIIllIIIIIIIIIIlllIIIlIllIIIIIIIIllIllIllIIIlIllIlIllIlIIIlIIIlIIlIIIlIlIllIlIIlIIIIIIIIIIIIIIllllIllIlIIIIIIlIIIIIlIIlIlllIlIIIllIIIIlIlIlIllIIIIlIIlllIIlIIIIIlIIllllIIIIlIIIllIIIIIllllllIlIllIIIlIlIIIllIllllIIlIIllIlIIllIIlIllllIlIIIIllIlllIIIlIIllIIIlIIIllIIlIIIllIlIIllIllIIlIIIIlIlllllllllIllIlIlIIlIIlllllIlIllIIIIIlIIlIllIlllIIlllIllIIIIIIIIlIllI(SourceFile:45)
[05:42:13 INFO]:        at me.kangarko.corearena.nul. .LPT8.llIllIllIIlllllllIlIIlIlIIIIIlIIlllIIlIlIIIllIIIlIIlIIlIlIlIlIllllIllIllIIlIlIIlIIlIIlllIIlIlllIlllllllIIlllIlllllllIllIIIIllIlIIIIIIlIllllIlIlllIlIlllIIIIlIllIllIlIIllIIllIlIlllIllIIIIlIlIlIIIIlllIlIllIllIlllIllIllIIIllIIllllIIIlllIllIIlIlllIlllIllIllIIllIIlllIlllIlIllIIlIIllIllllllIlIIlllIIllIIllIlIIIIIlllIIlllIIIlIIlllIlIIllllllllIIIIlIIlIllIlIllIlllIlIIlIlIlllIIllIlIllllIllIllIIlIIIIIlIIllIlllIIIIllllIllIIlIIIIIIlIIllIIIIllllIIIlIIIlIlllllIlIlIllIlIIllllllIllIIlIIIlIlIllllIIlIllIIIllIlllIlII(SourceFile:117)
[05:42:13 INFO]:        at me.kangarko.corearena.nul. .ai.IIlllIllllllIIIIIIlllllIIIlIIllIIlIIlIlIlIIlIllIIlIIIllIIIIllllIlllIlIllIllIlIIllllllllllIllIlIIlllIlIllIlIIIIIlIllllIlIIlllIlIIIlIlIlllllIIIlIlIIIIIIlIIIlIIllIlllIIlIllIlIlIIlllIIlllIIlIlIlllIlllllIllIIllllllIIIIllIlIllIlIIlIIlIlIlIlIIlIlIIIllllIlIlllllllllIIIlIlllIllIIIllIlIlIIIIlIllIIIIIlllllIIIlIlIIllllIllIlIIIIIIlllIIIlIlIIlIllIIllllIllIIlIIIIllIIIlIllIllllIllllIIlIllIlIIIIllIIIIllIIlIIIIIIIlIIIlIlIlllIllIIlIIlllllIlIllIlllIllIIIIIIlIIIlIlIlIllIlIIlIlllllllIlIllIlIIIIIIlIIllllIIllIIIIIlIIII(SourceFile:341)
[05:42:13 INFO]:        at me.kangarko.corearena.nul. .ai.a(SourceFile:330)
[05:42:13 INFO]:        at me.kangarko.corearena.nul. .a.nul(SourceFile:77)
[05:42:13 INFO]:        at me.kangarko.corearena.nul. .a.nul(SourceFile:73)
[05:42:13 INFO]:        at me.kangarko.corearena.nul. .interface$AUX.nul(SourceFile:118)
[05:42:13 INFO]:        at me.kangarko.corearena.nul. .interface.IlllllllIlIllIIlllIIllllIIlIlIlllIlllllIIIIlIllllllIlIIllIllIIlllIIlIIllIlIIllIllllIlIIlIIIlIllIllIlIIIIllIIllIIIIllllIlllIlIllIlIlIIlIIlllIIllIllllIIllIIIIIIIIIIlllIIIlIllIIIIIIIIllIllIllIIIlIllIlIllIlIIIlIIIlIIlIIIlIlIllIlIIlIIIIIIIIIIIIIIllllIllIlIIIIIIlIIIIIlIIlIlllIlIIIllIIIIlIlIlIllIIIIlIIlllIIlIIIIIlIIllllIIIIlIIIllIIIIIllllllIlIllIIIlIlIIIllIllllIIlIIllIlIIllIIlIllllIlIIIIllIlllIIIlIIllIIIlIIIllIIlIIIllIlIIllIllIIlIIIIlIlllllllllIllIlIlIIlIIlllllIlIllIIIIIlIIlIllIlllIIlllIllIIIIIIIIlIllI(SourceFile:56)
[05:42:13 INFO]:        at me.kangarko.corearena.nul. .interface.int(SourceFile:52)
[05:42:13 INFO]:        at me.kangarko.corearena.nul. .ai.onEnable(SourceFile:238)
[05:42:13 INFO]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254)
[05:42:13 INFO]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:325)
[05:42:13 INFO]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[05:42:13 INFO]:        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:441)
[05:42:13 INFO]:        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:355)
[05:42:13 INFO]:        at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:613)
[05:42:13 INFO]:        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:575)
[05:42:13 INFO]:        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:435)
[05:42:13 INFO]:        at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316)
[05:42:13 INFO]:        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:791)
[05:42:13 INFO]:        at java.lang.Thread.run(Unknown Source)
[05:42:13 INFO]:   _   _                       _
[05:42:13 INFO]:   | | | | ___   ___  _ __  ___| |
[05:42:13 INFO]:   | |_| |/ _ \ / _ \| '_ \/ __| |
[05:42:13 INFO]:   |  _  | (_) | (_) | |_) \__ \_|
[05:42:13 INFO]:   |_| |_|\___/ \___/| .__/|___(_)
[05:42:13 INFO]:                     |_|
[05:42:13 INFO]: !-----------------------------------------------------!
[05:42:13 INFO]:  Error loading CoreArena v1.7.18, plugin is disabled!
[05:42:13 INFO]:  Running on 1.13.2-R0.1-SNAPSHOT (v1_13_R2) & Java 1.8.0_191
[05:42:13 INFO]: !-----------------------------------------------------!
[05:42:13 INFO]:  Error: Unable to get the error message, search above.
[05:42:13 INFO]: !-----------------------------------------------------!

**Comment by kangarko** [comment]
Thanks, will be solved.
