### ISSUE TITLE
Load Bug

### ISSUE THREAD

**Issue by abode122** [kangarko/CoreArena#179]
Hello,

The plugin was greatly working and one day without any thing..the whole plugin stopped working and this bug showed up, could you please help me?

`Could not load 'plugins/CoreArena-1.7.23 (MC 1.12 and older).jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.ClassFormatError: Unknown constant tag 0 in class file me/kangarko/corearena/CoreArenaPlugin
at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[spigot.jar:git-Spigot-5f38d38-efd6cb0]
at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[spigot.jar:git-Spigot-5f38d38-efd6cb0]
at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [spigot.jar:git-Spigot-5f38d38-efd6cb0]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:292) [spigot.jar:git-Spigot-5f38d38-efd6cb0]
at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:198) [spigot.jar:git-Spigot-5f38d38-efd6cb0]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot.jar:git-Spigot-5f38d38-efd6cb0]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_192]
Caused by: java.lang.ClassFormatError: Unknown constant tag 0 in class file me/kangarko/corearena/CoreArenaPlugin
at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_192]
at java.lang.ClassLoader.defineClass(ClassLoader.java:763) ~[?:1.8.0_192]
at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_192]
at java.net.URLClassLoader.defineClass(URLClassLoader.java:468) ~[?:1.8.0_192]
at java.net.URLClassLoader.access$100(URLClassLoader.java:74) ~[?:1.8.0_192]
at java.net.URLClassLoader$1.run(URLClassLoader.java:369) ~[?:1.8.0_192]
at java.net.URLClassLoader$1.run(URLClassLoader.java:363) ~[?:1.8.0_192]
at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_192]
at java.net.URLClassLoader.findClass(URLClassLoader.java:362) ~[?:1.8.0_192]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot.jar:git-Spigot-5f38d38-efd6cb0]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-Spigot-5f38d38-efd6cb0]
at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_192]
at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_192]
at java.lang.Class.forName0(Native Method) ~[?:1.8.0_192]
at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_192]
at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[spigot.jar:git-Spigot-5f38d38-efd6cb0]
at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[spigot.jar:git-Spigot-5f38d38-efd6cb0]
... 6 more`

Have a nice day!

**Comment by kangarko** [comment]
Use the latest version please

**Comment by abode122** [comment]
Hello,

Sorry for the late reply, I had exams and took time to check out..
Just updated, about the same issue occurring..

Any ideas?

**Comment by kangarko** [comment]
Re-post the new error
