### ISSUE TITLE
Could not load CoreArena-1.8.8.jar

### ISSUE THREAD

**Issue by TheKasa** [kangarko/CoreArena#187]
[ERROR] Could not load 'plugins/CoreArena-1.8.8.jar' in folder 'plugins'

org.bukkit.plugin.UnknownDependencyException: GameAPI

at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:216) [spigot-1.13.2.jar:git-Spigot-078a7f5-a3c2ec0]

at org.bukkit.craftbukkit.v1_13_R2.CraftServer.loadPlugins(CraftServer.java:323) [spigot-1.13.2.jar:git-Spigot-078a7f5-a3c2ec0]

at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:213) [spigot-1.13.2.jar:git-Spigot-078a7f5-a3c2ec0]

at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:702) [spigot-1.13.2.jar:git-Spigot-078a7f5-a3c2ec0]

at java.lang.Thread.run(Thread.java:748) [?:1.8.0_192]

**Comment by TheKasa** [comment]
I just downloaded GameAPI and it fixed the issue
(https://www.spigotmc.org/resources/gameapi-1-7-10-1-13.48556/)
