### ISSUE TITLE
NoSuchMethodError - CoreArena 1.13.2

### ISSUE THREAD

**Issue by shadowriku459** [kangarko/CoreArena#205]
Hello there, this is what I see when being moved from an arena after the match has ended, and it results in no nuggets being rewarded either:

Error while removing player FearlessKage from Ocean
Moving him to spawn.
%error
NoSuchMethodError org.mineacademy.gameapi.ArenaCommands.runAsConsole(Lorg/mineacademy/gameapi/Arena;Lorg/bukkit/entity/Player;)V
	 at org.mineacademy.corearena.short. .aS.const(SourceFile:625)
	 at org.mineacademy.corearena.short. .aS.const(SourceFile:554)
	 at org.mineacademy.corearena.short. .aS.case(SourceFile:537)
	 at org.mineacademy.corearena.short. .aS.native(SourceFile:481)
	 at org.mineacademy.corearena.short. .aS.stopArena(SourceFile:423)
	 at org.mineacademy.corearena.short. .v.native(SourceFile:55)
	 at org.mineacademy.corearena.short. .cOm2.private(SourceFile:172)
	 at org.mineacademy.corearena.short. .LPt5.onCommand(SourceFile:61)
	 at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46)
	 at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
	 at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:704)

**Comment by kangarko** [comment]
Please update your GameAPI plugin as well as make sure CoreArena is at its latest release.
