### ISSUE TITLE
Potion stacks in Arena

### ISSUE THREAD

**Issue by shadowriku459** [kangarko/CoreArena#207]
Hiya,
So I get this error when adding potion stacks to a class and its upgraded tiers in the Arena class menu. Is there anyway to enable potion stacks without it causing this error?
I noticed it also resets my tiers for classes each time.

More Information: 
Report / Illegal size 5 != 54
Com6 Report / Report / Illegal size 5 != 54
	 at org.mineacademy.corearena.short. .COm2.const(SourceFile:75)
	 at org.mineacademy.corearena.short. .ab$AUX.const(SourceFile:187)
	 at org.mineacademy.corearena.short. .COm1.onMenuClose(SourceFile:39)
	 at sun.reflect.GeneratedMethodAccessor403.invoke(Unknown Source)
	 at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	 at java.lang.reflect.Method.invoke(Unknown Source)
	 at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:312)
	 at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66)
	 at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507)
	 at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492)
	 at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.handleInventoryCloseEvent(CraftEventFactory.java:1069)
----------------------------------------------------------------------------------------------

**Comment by kangarko** [comment]
Hi,

I could not trace that error back but I fixed that programatically. Let me know if you experience any more issues. Thanks.
