### ISSUE TITLE
Error while creating new class/setting price for tier upgrade.

### ISSUE THREAD

**Issue by shadowriku459** [kangarko/CoreArena#208]
More Information: 
Default '&2Guardian.yml' lacks a String at 'Tiers.2.Permission'
Com6 Report / Default '&2Guardian.yml' lacks a String at 'Tiers.2.Permission'
	 at org.mineacademy.corearena.short. .COm2.const(SourceFile:54)
	 at org.mineacademy.corearena.short. .COM8.strictfp(SourceFile:1020)
	 at org.mineacademy.corearena.short. .COM8.private(SourceFile:450)
	 at org.mineacademy.corearena.short. .COM8.transient(SourceFile:538)
	 at org.mineacademy.corearena.short. .try.native(SourceFile:58)
	 at org.mineacademy.corearena.short. .try.addOrUpdateTier(SourceFile:144)
	 at org.mineacademy.corearena.short. .ab$AUX.const(SourceFile:211)
	 at org.mineacademy.corearena.short. .COm1.onMenuClose(SourceFile:39)
	 at sun.reflect.GeneratedMethodAccessor306.invoke(Unknown Source)
	 at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	 at java.lang.reflect.Method.invoke(Unknown Source)
	 at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:312)
	 at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66)
	 at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507)
	 at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492)
	 at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.handleInventoryCloseEvent(CraftEventFactory.java:1069)

**Comment by shadowriku459** [comment]
Update: Decided to try making another and I noticed this error happens after I create a new class and exit the menu by 1 screen.
