### ISSUE TITLE
Error EntityDeathEvent v2.3.1

### ISSUE THREAD

**Issue by titidelaff** [kangarko/CoreArena#213]
` [14:08:34 ERROR]: Could not pass event EntityDeathEvent to CoreArena v2.3.1-BETA

java.lang.NoClassDefFoundError: org/mineacademy/boss/api/BossAPI
        at org.mineacademy.corearena.short. .interface.const(SourceFile:113) ~[?:?]
        at org.mineacademy.corearena.short. .else.const(SourceFile:62) ~[?:?]
        at org.mineacademy.corearena.short. .a.getExpFor(SourceFile:335) ~[?:?]
        at org.mineacademy.corearena.short. .v.onEntityDeath(SourceFile:293) ~[?:?]
        at org.mineacademy.corearena.short. .J.onEntityDeath(SourceFile:552) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor854.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.13.2.jar:git-Paper-629]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.13.2.jar:git-Paper-629]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[patched_1.13.2.jar:git-Paper-629]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:520) ~[patched_1.13.2.jar:git-Paper-629]
        at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:607) ~[patched_1.13.2.jar:git-Paper-629]
        at net.minecraft.server.v1_13_R2.EntityLiving.die(EntityLiving.java:1243) ~[patched_1.13.2.jar:git-Paper-629]
        at net.minecraft.server.v1_13_R2.EntityLiving.damageEntity(EntityLiving.java:1088) ~[patched_1.13.2.jar:git-Paper-629]
        at net.minecraft.server.v1_13_R2.EntityMonster.damageEntity(EntityMonster.java:44) ~[patched_1.13.2.jar:git-Paper-629]
        at net.minecraft.server.v1_13_R2.EntityHuman.attack(EntityHuman.java:1083) ~[patched_1.13.2.jar:git-Paper-629]
        at net.minecraft.server.v1_13_R2.EntityPlayer.attack(EntityPlayer.java:1492) ~[patched_1.13.2.jar:git-Paper-629]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:2011) ~[patched_1.13.2.jar:git-Paper-629]
        at net.minecraft.server.v1_13_R2.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:49) ~[patched_1.13.2.jar:git-Paper-629]
        at net.minecraft.server.v1_13_R2.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:6) ~[patched_1.13.2.jar:git-Paper-629]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15) ~[patched_1.13.2.jar:git-Paper-629]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_212]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_212]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[patched_1.13.2.jar:git-Paper-629]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1018) ~[patched_1.13.2.jar:git-Paper-629]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-629]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[patched_1.13.2.jar:git-Paper-629]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[patched_1.13.2.jar:git-Paper-629]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]`

**Comment by kangarko** [comment]
Hi, sorry for a late reply, please update your Boss version.
