### ISSUE TITLE
Classes window opening automatically in lobby fixed, but you now get kicked from arena

### ISSUE THREAD

**Issue by 8eeved** [kangarko/CoreArena#238]
Kanggarko, thanks heaps for a quick reply to the issue I was having in regards to the Classes window automatically opening in the lobby,  the classes window no longer opens which is what I was after, but now, signs to select a class within the lobby are disabled and players are  kicked from the lobby within a few seconds and the game ends, here is the error message via the console I am receiving::
[03:28:20] [Server thread/INFO]: !-----------------------------------------------------!
[03:28:20] [Server thread/INFO]: Error while joining Devee8 to Just_Deserts
[03:28:20] [Server thread/INFO]: Arena has been stopped for safety.
[03:28:20] [Server thread/INFO]: NoSuchMethodError: org.mineacademy.gameapi.ArenaSettings.openClassMenu()Z
[03:28:20] [Server thread/INFO]: !-----------------------------------------------------!
[03:28:20] [Server thread/INFO]: GG! The game in Just_Deserts has finished!
[03:28:29] [Server thread/INFO]: CoreArena 2.3.16 encountered a NoSuchMethodError! Please check your error.log and report this issue with the information in that file.
[03:28:29] [Server thread/INFO]: java.lang.NoSuchMethodError: org.mineacademy.gameapi.ArenaSettings.openClassMenu()Z
[03:28:29] [Server thread/INFO]: at org.mineacademy.corearena.short. .K.const(SourceFile:82)
[03:28:29] [Server thread/INFO]: at org.mineacademy.corearena.short. .M.native(SourceFile:268)
[03:28:29] [Server thread/INFO]: at org.mineacademy.corearena.short. .M.joinPlayer(SourceFile:160)
[03:28:29] [Server thread/INFO]: at org.mineacademy.corearena.short. .v.onSignOutGameClick(SourceFile:45)
[03:28:29] [Server thread/INFO]: at org.mineacademy.corearena.short. .aa.onPlayerInteract(SourceFile:269)
[03:28:29] [Server thread/INFO]: at sun.reflect.GeneratedMethodAccessor208.invoke(Unknown Source)
[03:28:29] [Server thread/INFO]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[03:28:29] [Server thread/INFO]: at java.lang.reflect.Method.invoke(Method.java:498)
[03:28:29] [Server thread/INFO]: at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316)
[03:28:29] [Server thread/INFO]: at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[03:28:29] [Server thread/INFO]: at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:529)
[03:28:29] [Server thread/INFO]: at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514)
[03:28:29] [Server thread/INFO]: at java.lang.Thread.run(Thread.java:748)
Thanking you in advance for any assistance you're able to offer.
Cheers, Mark.

**Comment by kangarko** [comment]
Please update your GameAPI https://www.spigotmc.org/resources/gameapi-1-7-10-1-14-4.48556
