### ISSUE TITLE
CoreArena 2.3.17 encountered a NoSuchMethodError

### ISSUE THREAD

**Issue by 8eeved** [kangarko/CoreArena#242]
Hi Kangarko,
Problems probably staring me in the face, This has been an issue since this current update
Clean install, crated the arena again, join and get teleported to the lobby.no visible count down and no response when clicking on the class sign. config file is pretty much the same since I began using your plugin, the option to turn off the class menu .while in the lobby was a nice option.
Any suggestions would be more than appreciated.
Cheers Mark.

------------------------------------[ 30.09.2019 03:00:49 ]-----------------------------------
CoreArena 2.3.17 encountered a NoSuchMethodError
Running Paper 1.14.4-R0.1-SNAPSHOT and Java 1.8.0_222
Plugins: Revenge v7.4.1-POST-1.14.4, PlaceholderAPI v2.10.4, PlugMan v2.1.6, GameAPI v3.1.1, CoreProtect v2.17.5, dynmap v3.0-beta-5-218, WorldEdit v7.0.1-rc1;edb2e91, PyroFishingPro v3.6.2, PyroMining v3.9.5, Votifier v2.5.0, HeadsPlus v6.6.3, LaggRemover v2.0.6, Multiverse-Core v4.1.0-b775, ProtocolLib v4.5.0-SNAPSHOT, AdvancedPortals v0.2.0, VotingPlugin v5.20.1, Minepacks v2.0.10-Release, PermissionsEx v1.23.4, Vault v1.7.2-b107, ServerListPlus v3.4.8, CrazyCrates v1.9.11, QuickShop vReremake 2.4.3.1, Holograms v2.9.1-SNAPSHOT, Essentials v2.17.1.0, GameModeInventories v3.1, Elevator v3.7.10, CommandSigns v2.1.2, Citizens v2.0.25-SNAPSHOT (build 1718), EssentialsChat v2.17.1.0, TAB v2.5.3, EssentialsProtect v2.17.1.0, EssentialsGeoIP v2.17.1.0, EssentialsAntiBuild v2.17.1.0, EssentialsSpawn v2.17.1.0, PrettySimpleShop v1.6.0-50892ad, Towny v0.94.0.0, WorldGuard v7.0.0;02b731f, EditableSign v7.0.4, TownyNameUpdater v2.0, TownyGUI v0.17, AreaShop v2.6.0#296, Jobs v4.13.1, Shopkeepers v2.7.1, RFChairs v6.0, GriefPrevention v16.12.0-d4d7ac4, DeathChestPro v3.3.6, SignShop v3.3.9, ItemsAdder v1.1.27, BigDoors vAlpha 0.1.8.13, Wild v2.10, UltimateTimber v1.0.14, CoreArena v2.3.17
----------------------------------------------------------------------------------------------

More Information: 
Error while joining Devee8 to Just_Deserts
Arena has been stopped for safety.
%error
NoSuchMethodError org.mineacademy.gameapi.ArenaSettings.openClassMenu()Z
	 at org.mineacademy.corearena.short. .K.const(SourceFile:82)
	 at org.mineacademy.corearena.short. .M.native(SourceFile:268)
	 at org.mineacademy.corearena.short. .M.joinPlayer(SourceFile:160)
	 at org.mineacademy.corearena.short. .v.onSignOutGameClick(SourceFile:45)
	 at org.mineacademy.corearena.short. .aa.onPlayerInteract(SourceFile:269)
	 at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor943.execute(Unknown Source)
	 at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
	 at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
	 at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
	 at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545)
	 at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:454)
-------------------------------------------------------------------------------------------

**Comment by kangarko** [comment]
Please update your GameAPI.
