### ISSUE TITLE
Nullpointer

### ISSUE THREAD

**Issue by Cerexus** [kangarko/CoreArena#244]
Hello, started creating an arena and now gott an nullpointer when i try to set the moster spawn with that iron ingot..

`Failed to handle RIGHT_CLICK_BLOCK using Tool: class org.mineacademy.corearena.short. .aR
NullPointerException (Unknown cause)
	 at java.base/java.util.Objects.requireNonNull(Objects.java:221)
	 at java.base/java.util.Arrays$ArrayList.<init>(Arrays.java:4323)
	 at java.base/java.util.Arrays.asList(Arrays.java:4310)
	 at org.mineacademy.corearena.short. .lPT5.const(SourceFile:1345)
	 at org.mineacademy.corearena.short. .D.toString(SourceFile:53)
	 at java.base/java.util.Formatter$FormatSpecifier.printString(Formatter.java:3031)
	 at java.base/java.util.Formatter$FormatSpecifier.print(Formatter.java:2908)
	 at java.base/java.util.Formatter.format(Formatter.java:2673)
	 at java.base/java.util.Formatter.format(Formatter.java:2609)
	 at java.base/java.lang.String.format(String.java:2897)
	 at org.mineacademy.corearena.lib.fo.collection.LpT7.private(SourceFile:152)
	 at org.mineacademy.corearena.short. .h.const(SourceFile:188)
	 at org.mineacademy.corearena.short. .h.while(SourceFile:165)
	 at org.mineacademy.corearena.short. .h.native(SourceFile:317)
	 at org.mineacademy.corearena.short. .h.addSpawnPoint(SourceFile:302)
	 at org.mineacademy.corearena.short. .aR.const(SourceFile:48)
	 at org.mineacademy.corearena.short. .Prn.const(SourceFile:87)
	 at org.mineacademy.corearena.short. .LpT6.onToolClick(SourceFile:77)
	 at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor159.execute(Unknown Source)
	 at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
	 at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
	 at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
	 at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545)
	 at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:454)`

**Comment by Cerexus** [comment]
after i got that error the playerspawnpoints get deleted or get useless and i cant place new player spawns (similar error).

**Comment by Cerexus** [comment]
[error.log](https://github.com/kangarko/CoreArena/files/3691782/error.log)

**Comment by 8eeved** [comment]
Finally got Arenas working again, now out of the blue having the same issue as Cerexus, no issues creating an arena until you place a mob spawner using the iron ingot.

**Comment by kangarko** [comment]
I am on it, should be fixed within 24-48 hours

**Comment by kangarko** [comment]
Thanks, addressed and fixed, new release on the way
