### ISSUE TITLE
Integration issue with DiscordSRV

### ISSUE THREAD

**Issue by pseud0** [kangarko/CoreArena#258]
Ever since DiscordSRV upgraded to version 1.18 I have been receiving errors in my log resulting in CoreArena not being loaded at server startup.

Refer below:

------------------------------------[ 12.11.2019 05:55:38 ]-----------------------------------
CoreArena 2.4.4 encountered a ClassNotFoundException
Running Paper 1.14.4-R0.1-SNAPSHOT and Java 1.8.0_222
Plugins: LuckPerms v4.4.1, WorldEdit v7.0.1;61bc012, PluginConstructorAPI v1.0.51, PlaceholderAPI v2.10.4, ClearLag v3.1.0, ajAntiXray v1.5, TangledMaze v1.3.3, Votifier v1.9, Multiverse-Core v4.1.0-b775, ProtocolLib v4.5.0-SNAPSHOT, LibsDisguises v9.8.2-SNAPSHOT, VotingPlugin v5.20.4, GameAPI v3.1.2, UltraPunishments v1.2.9, RandomTeleport v2.5.1, Multiverse-Portals v4.1.0-b805, PlayerParticles v6.5, WorldEditSelectionVisualizer v2.0.4, UltimateShops v2.0.4, WorldGuard v7.0.0;02b731f, mcMMO v2.1.110, Multiverse-NetherPortals v4.1.0-b763, CoreArena v2.4.4, NPCAuctions v1.0.62, RCChunkHopper v1.4.3, Vault v1.7.2-b107, GriefPrevention v16.12.0-d4d7ac4, AdvancedRegionMarket v2.1.0, UltraCosmetics v2.5.5, Essentials v2.17.1.0, VaultChatFormatter v1.0-SNAPSHOT, Elevator v3.7.12, MarketPlace v2.0.2, EpicLevels vmaven-version-number, Citizens v2.0.25-SNAPSHOT (build 1762), DiscordSRV v1.18.1-SNAPSHOT, EssentialsChat v2.17.1.0, EpicBosses vmaven-version-number, StaffPlus v3.3.0.0, EssentialsSpawn v2.17.1.0, ArmUltimateShopsBridge v1.0, StaffFacilities v4.1.6
----------------------------------------------------------------------------------------------

More Information: 
&cCoreArena could not integrate to DiscordSRV because the plugin is outdated!
ClassNotFoundException github.scarsz.discordsrv.dependencies.jda.core.entities.TextChannel
	 at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	 at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:139)
	 at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:85)
	 at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	 at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	 at java.lang.Class.forName0(Native Method)
	 at java.lang.Class.forName(Class.java:264)
	 at org.mineacademy.corearena.lib.fo.model.COM7.const(SourceFile:195)
	 at org.mineacademy.corearena.short. .coM4.onEnable(SourceFile:264)
	 at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
	 at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338)
	 at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420)
	 at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:467)
	 at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:381)
----------------------------------------------------------------------------------------------

**Comment by kangarko** [comment]
Sorry everyone for waiting, ever since I moved countries I find myself not having time for Spigot. 

I'm building a team with positions open for Java developers (paid), anyone feel free to apply [here](https://www.spigotmc.org/threads/403375/).

**This is now fixed.**
