### ISSUE TITLE
Need help with CoreArena after setting spawners

### ISSUE THREAD

**Issue by Edvyz** [kangarko/CoreArena#267]
what happened More Information: 
[12:49:45 INFO]: The game in arena has begun (2/8)!
[12:49:45 INFO]: CoreArena 2.4.8 encountered an IllegalArgumentException! Please check your error.log and report this issue with the information in that file.
[12:49:45 INFO]: java.lang.IllegalArgumentException: bound must be positive
[12:49:45 INFO]: at java.util.Random.nextInt(Random.java:388)
[12:49:45 INFO]: at org.mineacademy.corearena.short. .CON.native(SourceFile:135)
[12:49:45 INFO]: at org.mineacademy.corearena.short. .CON.const(SourceFile:155)
[12:49:45 INFO]: at org.mineacademy.corearena.short. .n.protected(SourceFile:374)
[12:49:45 INFO]: at org.mineacademy.corearena.short. .n.startTimer(SourceFile:490)
[12:49:45 INFO]: at org.mineacademy.corearena.short. .M.throw(SourceFile:397)
[12:49:45 INFO]: at org.mineacademy.corearena.short. .M.startArena(SourceFile:340)
[12:49:45 INFO]: at org.mineacademy.corearena.short. .new.native(SourceFile:25)
[12:49:45 INFO]: at org.mineacademy.corearena.lib.fo.model.Com2.run(SourceFile:71)
[12:49:45 INFO]: at java.lang.Thread.run(Thread.java:748)
[12:49:45 INFO]: !-----------------------------------------------------!
[12:49:45 INFO]: Error while spawning mobs in arena
[12:49:45 INFO]: IllegalArgumentException: bound must be positive
[12:49:45 INFO]: Stopping arena for safety.
[12:49:45 INFO]: !-----------------------------------------------------!

[Naujas WinRAR ZIP archyvas.zip](https://github.com/kangarko/CoreArena/files/3991697/Naujas.WinRAR.ZIP.archyvas.zip)

**Comment by lackoSK** [comment]
Hey, can you remove the spawners and start arena wo them? (I need to be sure where is the issue  coming from)

**Comment by JavaFactoryDev** [comment]
User not responding.
