### ISSUE TITLE
Paper 1.15.2 - CoreArena + Boss breaks the Arena

### ISSUE THREAD

**Issue by gaRt3n** [kangarko/CoreArena#278]
Hey there,

I got a Problem with Boss in Combination with CoreArena. It stops working after wave 5
Items drops from dead mobs and dead players.

[CHAT] This server is running Paper version git-Paper-65 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

`[03:09:18 ERROR]: Could not pass event EntityDeathEvent to CoreArena v2.5.4
java.lang.NoClassDefFoundError: org/mineacademy/corearena/lib/boss/api/BossAPI
        at org.mineacademy.corearena.short. .double.const(SourceFile:120) ~[?:?]
        at org.mineacademy.corearena.short. .synchronized.const(SourceFile:62) ~[?:?]
        at org.mineacademy.corearena.short. .q.getExpFor(SourceFile:342) ~[?:?]
        at org.mineacademy.corearena.short. .L.onEntityDeath(SourceFile:293) ~[?:?]
        at org.mineacademy.corearena.short. .Z.onEntityDeath(SourceFile:506) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor718.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-65]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-65]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-65]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.15.2.jar:git-Paper-65]
        at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:754) ~[patched_1.15.2.jar:git-Paper-65]
        at net.minecraft.server.v1_15_R1.EntityLiving.d(EntityLiving.java:1380) ~[patched_1.15.2.jar:git-Paper-65]
        at net.minecraft.server.v1_15_R1.EntityLiving.die(EntityLiving.java:1308) ~[patched_1.15.2.jar:git-Paper-65]
        at net.minecraft.server.v1_15_R1.EntityLiving.damageEntity(EntityLiving.java:1152) ~[patched_1.15.2.jar:git-Paper-65]
        at net.minecraft.server.v1_15_R1.EntityArrow.a(EntityArrow.java:378) ~[patched_1.15.2.jar:git-Paper-65]
        at net.minecraft.server.v1_15_R1.EntityArrow.a(EntityArrow.java:291) ~[patched_1.15.2.jar:git-Paper-65]
        at net.minecraft.server.v1_15_R1.EntityArrow.tick(EntityArrow.java:202) ~[patched_1.15.2.jar:git-Paper-65]
        at net.minecraft.server.v1_15_R1.EntityTippedArrow.tick(EntityTippedArrow.java:92) ~[patched_1.15.2.jar:git-Paper-65]
        at net.minecraft.server.v1_15_R1.WorldServer.entityJoinedWorld(WorldServer.java:734) ~[patched_1.15.2.jar:git-Paper-65]
        at net.minecraft.server.v1_15_R1.World.a(World.java:878) ~[patched_1.15.2.jar:git-Paper-65]
        at net.minecraft.server.v1_15_R1.WorldServer.doTick(WorldServer.java:497) ~[patched_1.15.2.jar:git-Paper-65]
        at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1245) ~[patched_1.15.2.jar:git-Paper-65]
        at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:423) ~[patched_1.15.2.jar:git-Paper-65]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1112) ~[patched_1.15.2.jar:git-Paper-65]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934) ~[patched_1.15.2.jar:git-Paper-65]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
[03:09:20 ERROR]: Could not pass event EntityDeathEvent to CoreArena v2.5.4
java.lang.NoClassDefFoundError: org/mineacademy/corearena/lib/boss/api/BossAPI
        at org.mineacademy.corearena.short. .double.const(SourceFile:120) ~[?:?]
        at org.mineacademy.corearena.short. .synchronized.const(SourceFile:62) ~[?:?]
        at org.mineacademy.corearena.short. .q.getExpFor(SourceFile:342) ~[?:?]
        at org.mineacademy.corearena.short. .L.onEntityDeath(SourceFile:293) ~[?:?]
        at org.mineacademy.corearena.short. .Z.onEntityDeath(SourceFile:506) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor718.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-65]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-65]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-65]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.15.2.jar:git-Paper-65]
        at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:754) ~[patched_1.15.2.jar:git-Paper-65]
        at net.minecraft.server.v1_15_R1.EntityLiving.d(EntityLiving.java:1380) ~[patched_1.15.2.jar:git-Paper-65]
        at net.minecraft.server.v1_15_R1.EntityLiving.die(EntityLiving.java:1308) ~[patched_1.15.2.jar:git-Paper-65]
        at net.minecraft.server.v1_15_R1.EntityLiving.damageEntity(EntityLiving.java:1152) ~[patched_1.15.2.jar:git-Paper-65]
        at net.minecraft.server.v1_15_R1.EntityMonster.damageEntity(EntityMonster.java:52) ~[patched_1.15.2.jar:git-Paper-65]
        at net.minecraft.server.v1_15_R1.EntityZombie.damageEntity(EntityZombie.java:318) ~[patched_1.15.2.jar:git-Paper-65]
        at net.minecraft.server.v1_15_R1.EntityWolf.B(EntityWolf.java:253) ~[patched_1.15.2.jar:git-Paper-65]
        at net.minecraft.server.v1_15_R1.PathfinderGoalMeleeAttack.a(SourceFile:139) ~[patched_1.15.2.jar:git-Paper-65]
        at net.minecraft.server.v1_15_R1.PathfinderGoalMeleeAttack.e(SourceFile:131) ~[patched_1.15.2.jar:git-Paper-65]
        at net.minecraft.server.v1_15_R1.PathfinderGoalWrapped.e(SourceFile:55) ~[patched_1.15.2.jar:git-Paper-65]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:1.8.0_242]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_242]
        at java.util.Iterator.forEachRemaining(Iterator.java:116) ~[?:1.8.0_242]
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:1.8.0_242]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_242]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_242]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:1.8.0_242]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:1.8.0_242]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_242]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485) ~[?:1.8.0_242]
        at net.minecraft.server.v1_15_R1.PathfinderGoalSelector.doTick(PathfinderGoalSelector.java:114) ~[patched_1.15.2.jar:git-Paper-65]
        at net.minecraft.server.v1_15_R1.EntityInsentient.doTick(EntityInsentient.java:679) ~[patched_1.15.2.jar:git-Paper-65]
        at net.minecraft.server.v1_15_R1.EntityLiving.movementTick(EntityLiving.java:2596) ~[patched_1.15.2.jar:git-Paper-65]
        at net.minecraft.server.v1_15_R1.EntityInsentient.movementTick(EntityInsentient.java:517) ~[patched_1.15.2.jar:git-Paper-65]
        at net.minecraft.server.v1_15_R1.EntityAgeable.movementTick(EntityAgeable.java:171) ~[patched_1.15.2.jar:git-Paper-65]
        at net.minecraft.server.v1_15_R1.EntityAnimal.movementTick(EntityAnimal.java:28) ~[patched_1.15.2.jar:git-Paper-65]
        at net.minecraft.server.v1_15_R1.EntityWolf.movementTick(EntityWolf.java:151) ~[patched_1.15.2.jar:git-Paper-65]
        at net.minecraft.server.v1_15_R1.EntityLiving.tick(EntityLiving.java:2383) ~[patched_1.15.2.jar:git-Paper-65]
        at net.minecraft.server.v1_15_R1.EntityInsentient.tick(EntityInsentient.java:286) ~[patched_1.15.2.jar:git-Paper-65]
        at net.minecraft.server.v1_15_R1.EntityWolf.tick(EntityWolf.java:167) ~[patched_1.15.2.jar:git-Paper-65]
        at net.minecraft.server.v1_15_R1.WorldServer.entityJoinedWorld(WorldServer.java:734) ~[patched_1.15.2.jar:git-Paper-65]
        at net.minecraft.server.v1_15_R1.World.a(World.java:878) ~[patched_1.15.2.jar:git-Paper-65]
        at net.minecraft.server.v1_15_R1.WorldServer.doTick(WorldServer.java:497) ~[patched_1.15.2.jar:git-Paper-65]
        at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1245) ~[patched_1.15.2.jar:git-Paper-65]
        at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:423) ~[patched_1.15.2.jar:git-Paper-65]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1112) ~[patched_1.15.2.jar:git-Paper-65]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934) ~[patched_1.15.2.jar:git-Paper-65]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
[03:09:23 ERROR]: Could not pass event EntityDeathEvent to CoreArena v2.5.4
java.lang.NoClassDefFoundError: org/mineacademy/corearena/lib/boss/api/BossAPI
        at org.mineacademy.corearena.short. .double.const(SourceFile:120) ~[?:?]
        at org.mineacademy.corearena.short. .synchronized.const(SourceFile:62) ~[?:?]
        at org.mineacademy.corearena.short. .q.getExpFor(SourceFile:342) ~[?:?]
        at org.mineacademy.corearena.short. .L.onEntityDeath(SourceFile:293) ~[?:?]
        at org.mineacademy.corearena.short. .Z.onEntityDeath(SourceFile:506) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor718.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-65]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-65]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-65]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.15.2.jar:git-Paper-65]
        at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:754) ~[patched_1.15.2.jar:git-Paper-65]
        at net.minecraft.server.v1_15_R1.EntityLiving.d(EntityLiving.java:1380) ~[patched_1.15.2.jar:git-Paper-65]
        at net.minecraft.server.v1_15_R1.EntityLiving.die(EntityLiving.java:1308) ~[patched_1.15.2.jar:git-Paper-65]
        at net.minecraft.server.v1_15_R1.EntityLiving.damageEntity(EntityLiving.java:1152) ~[patched_1.15.2.jar:git-Paper-65]
        at net.minecraft.server.v1_15_R1.EntityMonster.damageEntity(EntityMonster.java:52) ~[patched_1.15.2.jar:git-Paper-65]
        at net.minecraft.server.v1_15_R1.EntityZombie.damageEntity(EntityZombie.java:318) ~[patched_1.15.2.jar:git-Paper-65]
        at net.minecraft.server.v1_15_R1.EntityArrow.a(EntityArrow.java:378) ~[patched_1.15.2.jar:git-Paper-65]
        at net.minecraft.server.v1_15_R1.EntityArrow.a(EntityArrow.java:291) ~[patched_1.15.2.jar:git-Paper-65]
        at net.minecraft.server.v1_15_R1.EntityArrow.tick(EntityArrow.java:202) ~[patched_1.15.2.jar:git-Paper-65]
        at net.minecraft.server.v1_15_R1.EntityTippedArrow.tick(EntityTippedArrow.java:92) ~[patched_1.15.2.jar:git-Paper-65]
        at net.minecraft.server.v1_15_R1.WorldServer.entityJoinedWorld(WorldServer.java:734) ~[patched_1.15.2.jar:git-Paper-65]
        at net.minecraft.server.v1_15_R1.World.a(World.java:878) ~[patched_1.15.2.jar:git-Paper-65]
        at net.minecraft.server.v1_15_R1.WorldServer.doTick(WorldServer.java:497) ~[patched_1.15.2.jar:git-Paper-65]
        at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1245) ~[patched_1.15.2.jar:git-Paper-65]
        at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:423) ~[patched_1.15.2.jar:git-Paper-65]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1112) ~[patched_1.15.2.jar:git-Paper-65]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934) ~[patched_1.15.2.jar:git-Paper-65]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
[03:09:24 ERROR]: Could not pass event EntityDeathEvent to CoreArena v2.5.4
java.lang.NoClassDefFoundError: org/mineacademy/corearena/lib/boss/api/BossAPI
        at org.mineacademy.corearena.short. .double.const(SourceFile:120) ~[?:?]
        at org.mineacademy.corearena.short. .synchronized.const(SourceFile:62) ~[?:?]
        at org.mineacademy.corearena.short. .q.getExpFor(SourceFile:342) ~[?:?]
        at org.mineacademy.corearena.short. .L.onEntityDeath(SourceFile:293) ~[?:?]
        at org.mineacademy.corearena.short. .Z.onEntityDeath(SourceFile:506) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor718.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-65]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-65]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-65]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.15.2.jar:git-Paper-65]
        at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:754) ~[patched_1.15.2.jar:git-Paper-65]
        at net.minecraft.server.v1_15_R1.EntityLiving.d(EntityLiving.java:1380) ~[patched_1.15.2.jar:git-Paper-65]
        at net.minecraft.server.v1_15_R1.EntityLiving.die(EntityLiving.java:1308) ~[patched_1.15.2.jar:git-Paper-65]
        at net.minecraft.server.v1_15_R1.EntityLiving.damageEntity(EntityLiving.java:1152) ~[patched_1.15.2.jar:git-Paper-65]
        at net.minecraft.server.v1_15_R1.EntityMonster.damageEntity(EntityMonster.java:52) ~[patched_1.15.2.jar:git-Paper-65]
        at net.minecraft.server.v1_15_R1.EntityZombie.damageEntity(EntityZombie.java:318) ~[patched_1.15.2.jar:git-Paper-65]
        at net.minecraft.server.v1_15_R1.EntityArrow.a(EntityArrow.java:378) ~[patched_1.15.2.jar:git-Paper-65]
        at net.minecraft.server.v1_15_R1.EntityArrow.a(EntityArrow.java:291) ~[patched_1.15.2.jar:git-Paper-65]
        at net.minecraft.server.v1_15_R1.EntityArrow.tick(EntityArrow.java:202) ~[patched_1.15.2.jar:git-Paper-65]
        at net.minecraft.server.v1_15_R1.EntityTippedArrow.tick(EntityTippedArrow.java:92) ~[patched_1.15.2.jar:git-Paper-65]
        at net.minecraft.server.v1_15_R1.WorldServer.entityJoinedWorld(WorldServer.java:734) ~[patched_1.15.2.jar:git-Paper-65]
        at net.minecraft.server.v1_15_R1.World.a(World.java:878) ~[patched_1.15.2.jar:git-Paper-65]
        at net.minecraft.server.v1_15_R1.WorldServer.doTick(WorldServer.java:497) ~[patched_1.15.2.jar:git-Paper-65]
        at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1245) ~[patched_1.15.2.jar:git-Paper-65]
        at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:423) ~[patched_1.15.2.jar:git-Paper-65]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1112) ~[patched_1.15.2.jar:git-Paper-65]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934) ~[patched_1.15.2.jar:git-Paper-65]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
[03:09:26 INFO]: CoreArena 2.5.4 encountered a NoClassDefFoundError! Please check your error.log and report this issue with the information in that file.
[03:09:26 INFO]: java.lang.NoClassDefFoundError: org/mineacademy/corearena/lib/boss/api/BossAPI
[03:09:26 INFO]: at org.mineacademy.corearena.short. .double.const(SourceFile:111)
[03:09:26 INFO]: at org.mineacademy.corearena.short. .synchronized.native(SourceFile:55)
[03:09:26 INFO]: at org.mineacademy.corearena.short. .o.protected(SourceFile:402)
[03:09:26 INFO]: at org.mineacademy.corearena.short. .o.onNextPhase(SourceFile:195)
[03:09:26 INFO]: at org.mineacademy.corearena.short. .char.const(SourceFile:24)
[03:09:26 INFO]: at org.mineacademy.corearena.lib.fo.model.Com2.run(SourceFile:59)
[03:09:26 INFO]: at java.lang.Thread.run(Thread.java:748)
[03:09:26 INFO]: !-----------------------------------------------------!
[03:09:26 INFO]: Arena Trains has failed entering phase: 6
[03:09:26 INFO]: Stopping arena for safety.
[03:09:26 INFO]: NoClassDefFoundError: org/mineacademy/corearena/lib/boss/api/BossAPI
[03:09:26 INFO]: !-----------------------------------------------------!
[03:09:26 INFO]: GG! Das Spiel in Trains  ist beendet.!`

**Comment by JavaFactoryDev** [comment]
Hey  gaTr3N,

Thank you for using CoreArena & taking the time to report this issue.

However, this issue is already known and solved & please update to the latest version of boss.

Regards,
- Leonhard from MineAcademy

**Comment by gaRt3n** [comment]
It was the latest build i got.
`------------------------------------[ 16.02.2020 03:09:26 ]-----------------------------------
CoreArena 2.5.4 encountered a NoClassDefFoundError
Running Paper 1.15.2-R0.1-SNAPSHOT and Java 1.8.0_242
Plugins: LuckPerms v5.0.77, WorldEdit v7.1.0-SNAPSHOT;4822-a27ade5, EntityTrackerFixer v1.2.2, PlaceholderAPI v2.10.4, VillagerOptimiser v1.1.2, Craftconomy3 v3.3.1-d99cf63-trv200, Boss v3.6.8, PlugMan v2.1.6, Votifier v3.0.0-SNAPSHOT, Multiverse-Core v4.1.0-b775, ProtocolLib v4.5.0, WorldGuard v7.0.3-SNAPSHOT;2004-d37f015, ItemMetarizer v1.1, LocalExecute v1.0.0, VotingPlugin v5.20.5, MaSuiteCore v1.5.5-SNAPSHOT, GameAPI v3.1.2, WorldEditGlobalizerBukkit v1.3.6, VoidGenerator v1.4.2, Sudo v1, TopiWings v1.0, TopiCoreTickets v1.4, MaSuiteHomes v1.2.9.4, ServerConnect v1.11.2, LimitPillagers v2.12.0, XenforoSignup v1.2.0, CraftingStore v2.2.1, Vault v1.7.2-b107, PlayerParticles v6.6, BungeeTabListPlus v2.8.12, GlobalExecute v1.0, MaSuiteWarps v1.4.7.5, MaSuiteTeleports v1.3.5, ChatControl v8.6.0, CMI v8.6.19.1, ChestCommands v3.5.2, MythicMobs v4.6.5-2800, Plan v5.0 build 335, CoreArena v2.5.4
----------------------------------------------------------------------------------------------

More Information: 
Arena Trains has failed entering phase: 6
Stopping arena for safety.
%error
NoClassDefFoundError org/mineacademy/corearena/lib/boss/api/BossAPI
	 at org.mineacademy.corearena.short. .double.const(SourceFile:111)
	 at org.mineacademy.corearena.short. .synchronized.native(SourceFile:55)
	 at org.mineacademy.corearena.short. .o.protected(SourceFile:402)
	 at org.mineacademy.corearena.short. .o.onNextPhase(SourceFile:195)
	 at org.mineacademy.corearena.short. .char.const(SourceFile:24)
	 at org.mineacademy.corearena.lib.fo.model.Com2.run(SourceFile:59)
	 at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84)
	 at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452)
----------------------------------------------------------------------------------------------
`

**Comment by JavaFactoryDev** [comment]
Hey gaRt3n,

Thank you for reporting this issue:)
We hope it is now fixed with the latest version of CoreArena.

Regards,
- Leonhard from MineAcademy
