### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Cerexus** [kangarko/CoreArena#299]
Have this issue since january. Newest CoreArena and Boss...  Please fix that

[21:02:09 INFO]: CoreArena 2.5.9 encountered a NoClassDefFoundError! Please check your error.log and report this issue with the information in that file.
[21:02:09 INFO]: java.lang.NoClassDefFoundError: org/mineacademy/corearena/lib/boss/api/BossAPI
[21:02:09 INFO]: at org.mineacademy.corearena.short. .ds.a(SourceFile:111)
[21:02:09 INFO]: at org.mineacademy.corearena.short. .dt.b(SourceFile:55)
[21:02:09 INFO]: at org.mineacademy.corearena.short. .dN.f(SourceFile:402)
[21:02:09 INFO]: at org.mineacademy.corearena.short. .dN.startTimer(SourceFile:490)
[21:02:09 INFO]: at org.mineacademy.corearena.short. .em.j(SourceFile:397)
[21:02:09 INFO]: at org.mineacademy.corearena.short. .em.startArena(SourceFile:340)
[21:02:09 INFO]: at org.mineacademy.corearena.short. .df.c(SourceFile:25)
[21:02:09 INFO]: at org.mineacademy.corearena.lib.fo.model.k.run(SourceFile:92)
[21:02:09 INFO]: at java.lang.Thread.run(Thread.java:748)
[21:02:09 INFO]: java.lang.ClassNotFoundException: org.mineacademy.corearena.lib.boss.api.BossAPI
[21:02:09 INFO]: at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
[21:02:09 INFO]: at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:171)
[21:02:09 INFO]: at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100)
[21:02:09 INFO]: at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
[21:02:09 INFO]: at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
[21:02:09 INFO]: at org.mineacademy.corearena.short. .ds.a(SourceFile:111)
[21:02:09 INFO]: at org.mineacademy.corearena.short. .dt.b(SourceFile:55)
[21:02:09 INFO]: at org.mineacademy.corearena.short. .dN.f(SourceFile:402)
[21:02:09 INFO]: at org.mineacademy.corearena.short. .dN.startTimer(SourceFile:490)
[21:02:09 INFO]: at org.mineacademy.corearena.short. .em.j(SourceFile:397)
[21:02:09 INFO]: at org.mineacademy.corearena.short. .em.startArena(SourceFile:340)
[21:02:09 INFO]: at org.mineacademy.corearena.short. .df.c(SourceFile:25)
[21:02:09 INFO]: at org.mineacademy.corearena.lib.fo.model.k.run(SourceFile:92)
[21:02:09 INFO]: at java.lang.Thread.run(Thread.java:748)
[21:02:09 INFO]: !-----------------------------------------------------!
[21:02:09 INFO]: Error while spawning mobs in The_Village
[21:02:09 INFO]: ClassNotFoundException: org.mineacademy.corearena.lib.boss.api.BossAPI
[21:02:09 INFO]: Stopping arena for safety.
[21:02:09 INFO]: !-----------------------------------------------------!
[21:02:09 INFO]: GG! The game in The_Village has finished!

**Comment by JavaFactoryDev** [comment]
This issue is already known and is already fixed with the latest version of CoreArena which will be released soon:)
