### ISSUE TITLE
It wont work

### ISSUE THREAD

**Issue by lerndmina** [kangarko/CoreArena#30]
None of the commands in core arena work and the plugin is showing up as red in my plugins list

Latest error
`------------------------------------[ 03.11.2017 15:12:29 ]-----------------------------------
CoreArena 1.4.4 encountered a NoClassDefFoundError
Running 1.8-R0.1-SNAPSHOT and Java 1.8.0_144
Plugins: AdvancedPortals v0.0.35, WorldEdit v6.1.8-SNAPSHOT;cd4729f, GameAPI v1.0.4, PermissionsEx v1.23.4, PlugMan v2.1.4, Vault v1.5.6-b49, BetterNick v4.3, MassiveCore v2.13.2, The Multiverse-Core Plugin, QuickSell v2.0.6, ColoredTags v2.1.3, Essentials v2.0.1-b488, Multiverse-Inventories v1.4, HolographicDisplays v2.2.6, SignShop v2.11.2, CoreArena v1.4.4, KitAdder v2.6, Factions v2.13.2
----------------------------------------------------------------------------------------------

More Information: 
Plugin shutdown malfunction: NoClassDefFoundError
NoClassDefFoundErrorcom/google/gson/JsonSyntaxException
	 at me.kangarko.corearena.nul. .AUX.IlIIlIIlIIIlIIIIllllIllllllllllllIIIIlIlIIIllllllIIllIIIIlllIIIIlIllIIIllIIllIIllIllIlllIIllIIlIllllIlIIlIllIIlIIIIllIllIIllIIllIllIlIIIIIlIIIllIlIIIllIIlllIlIIIIlIIIIlIIIllIlllllllIllIllIIllIIIIIIIIIllllIIlIlllIllIIlIlIIIllIllllIllllIIIlIIlllIllIlIlIIIIIIIlIIIIlIlIlIIIIIllIlIllllIllllIlIllIIlllIIIllIIllIIIllIIIIllIIlIIlIllIllIIlIIllllIlIlllIlIllllllllIIIIlIIlIllllllllIllIIlllIllIllllIllIllllIIlllIIllIIllIIIIllllllIIlIlllIlIIllllIIllIllIlllIlIIIIlIIIlIlIIIIlIIlIIIlIlllIlIlIllllIIlllllIIllIIIIlll(SourceFile:209)
	 at me.kangarko.corearena.nul. .AUX.IIlllIllllllIIIIIIlllllIIIlIIllIIlIIlIlIlIIlIllIIlIIIllIIIIllllIlllIlIllIllIlIIllllllllllIllIlIIlllIlIllIlIIIIIlIllllIlIIlllIlIIIlIlIlllllIIIlIlIIIIIIlIIIlIIllIlllIIlIllIlIlIIlllIIlllIIlIlIlllIlllllIllIIllllllIIIIllIlIllIlIIlIIlIlIlIlIIlIlIIIllllIlIlllllllllIIIlIlllIllIIIllIlIlIIIIlIllIIIIIlllllIIIlIlIIllllIllIlIIIIIIlllIIIlIlIIlIllIIllllIllIIlIIIIllIIIlIllIllllIllllIIlIllIlIIIIllIIIIllIIlIIIIIIIlIIIlIlIlllIllIIlIIlllllIlIllIlllIllIIIIIIlIIIlIlIlIllIlIIlIlllllllIlIllIlIIIIIIlIIllllIIllIIIIIlIIII(SourceFile:187)
	 at me.kangarko.corearena.nul. .T.onDisable(SourceFile:325)
	 at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:323)
	 at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:359)
	 at me.kangarko.corearena.nul. .T.nul(SourceFile:299)
	 at me.kangarko.corearena.nul. .T.onEnable(SourceFile:180)
	 at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
	 at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335)
	 at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
	 at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugin(CraftServer.java:356)
	 at org.bukkit.craftbukkit.v1_8_R1.CraftServer.enablePlugins(CraftServer.java:316)
----------------------------------------------------------------------------------------------

`

**Comment by kangarko** [comment]
Hey,

thank you for informing me. Please make sure you did not reload but did a fresh restart.

All in all, I have made some changes, please test out the next version.

**Comment by kangarko** [comment]
Closing this in faith that this has been resolved, please remind me if not.
