### ISSUE TITLE
1.12.2 CoreArena not working: Not even starting the arenas.

### ISSUE THREAD

**Issue by TonyMontero** [kangarko/CoreArena#300]
**Issue:** Mobs aren't spawning from the spawners. First of all they weren't saving themselves and not they're not capable to work with.

**Version:** MCPaper 1.12.2 (lastest build 1618).

**Files:** Here we go with the files.

**Plugins used:** The required to make it work, that includes..
_- CoreArena 2.5.9
- GameAPI 3.1.2
- Multiverse-Core 2.5
- Multiverse-Portals 2.5.0
- Vault
- WorldEdit 6.1.9
- WorldGuard 6.2.1
- WorldEditBridge 2.1.0_

[CoreArena.zip](https://github.com/kangarko/CoreArena/files/4463545/CoreArena.zip)

**Comment by JavaFactoryDev** [comment]
Hey TonyMontero,

Thank you for reporting this issue.
I've tested the mob-spawning and it went pretty well.

However, the mob-spawning is bound to vanilla mob-spawning.

Di you sure the gamerule allow-mob-spawning is set to true & there are now other regions
interfering with it?

Regards,
- Leonhard from MineAcademy

**Comment by TonyMontero** [comment]
Hey there, it works now i was using the /corearena egg zombie instead of the vanilla one.
Moving to another theme:

```
[10:56:37 INFO]: CoreArena 2.5.9 encountered an ap! Please check your error.log and report this issue with the information in that file.
[10:56:37 ERROR]: Could not pass event InventoryCloseEvent to CoreArena v2.5.9
org.bukkit.event.EventException: null
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.12.2.jar:git-Paper-1618]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.handleInventoryCloseEvent(CraftEventFactory.java:982) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.EntityPlayer.closeInventory(EntityPlayer.java:999) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.craftbukkit.v1_12_R1.entity.CraftHumanEntity.closeInventory(CraftHumanEntity.java:405) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.mineacademy.corearena.short. .aT.a(SourceFile:139) ~[?:?]
        at org.mineacademy.corearena.short. .aI.a(SourceFile:403) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:840) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1618]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
Caused by: org.mineacademy.corearena.short. .ap: Report / Could not detect monster type from ItemStack{MONSTER_EGG x 1, SPAWN_EGG_META:{meta-type=SPAWN_EGG, display-name=§r§rSpawn Zombie, lore=[§7, §7Place this item in your, §7monster spawner to, §7summon Zombie], enchants={DURABILITY=1}, ItemFlags=[HIDE_ENCHANTS, HIDE_ATTRIBUTES, HIDE_UNBREAKABLE, HIDE_DESTROYS, HIDE_PLACED_ON, HIDE_POTION_EFFECTS], internal=H4sIAAAAAAAAAONiYOBiEHDOL0p1LErNS4z3SyoJSUznYOBwT8xNjXdNT2dgi/L3dfJ0ZWAAAL34k6orAAAA}} (data = SPAWN EGG{null}, dura = 0)
        at org.mineacademy.corearena.short. .A.a(SourceFile:57) ~[?:?]
        at org.mineacademy.corearena.short. .bw.a(SourceFile:97) ~[?:?]
        at org.mineacademy.corearena.short. .ej.a(SourceFile:68) ~[?:?]
        at org.mineacademy.corearena.short. .eZ$a.b(SourceFile:207) ~[?:?]
        at org.mineacademy.corearena.short. .f.a(SourceFile:1710) ~[?:?]
        at org.mineacademy.corearena.short. .eZ$a.a(SourceFile:207) ~[?:?]
        at org.mineacademy.corearena.short. .aJ.onMenuClose(SourceFile:39) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor213.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1618]
        ... 15 more
```

This shows up right now.

**Comment by kangarko** [comment]
@JavaFactoryDev please take a look as soon as possible

**Comment by JhueiGitHub** [comment]
Any bump on this? Having the same problem.

**Comment by kangarko** [comment]
@JavaFactoryDev please prioritize

**Comment by kangarko** [comment]
@JavaFactoryDev

**Comment by JavaFactoryDev** [comment]
I was unable to find the issue yet.
I will ask my teammates to fix this issue

**Comment by JavaFactoryDev** [comment]
Hey please update your CoreArena to the latest version.
I've tested it multiple times and its working pretty fine for me.

![Arena](https://cdn.discordapp.com/attachments/360422594769584128/712978381452345444/2020-05-21_12.39.34.png)

Regards,
Leonhard from MineAcademy
