### ISSUE TITLE
Error when starting the arena

### ISSUE THREAD

**Issue by pustinek** [kangarko/CoreArena#305]
Error is thrown at the start of the arena which in turn stops the arena.
```
------------------------------------[ 15.04.2020 09:54:42 ]-----------------------------------
CoreArena 2.5.9 encountered an ap
Running Paper 1.15.2-R0.1-SNAPSHOT and Java 1.8.0_242
Plugins: LuckPerms v5.0.117, WorldEdit v7.1.0;8e55131, AsyncWorldEdit v3.6.19, GameAPI v3.1.2, Essentials v2.17.2.0, ArenaTeleport v2.0.0, PlaceholderAPI v2.10.4, HeadDatabase v4.12.1, EssentialsSpawn v2.17.2.0, BungeeTabListPlus v2.8.11, ProtocolLib v4.5.0, WorldGuard v7.0.2-SNAPSHOT;bf2593e, DeluxeChat v1.15.0, LibsDisguises v10.0.3, PhatLoots v5.4.0, MythicMobs v4.9.0-3254, CoreArena v2.5.9
----------------------------------------------------------------------------------------------

More Information: 
No messages to debug at section:  monsters alive = 4
ap Report / No messages to debug at section:  monsters alive = 4
	 at org.mineacademy.corearena.short. .A.a(SourceFile:57)
	 at org.mineacademy.corearena.short. .ag.a(SourceFile:120)
	 at org.mineacademy.corearena.short. .dN.onNextPhase(SourceFile:159)
	 at org.mineacademy.corearena.short. .dh.b(SourceFile:24)
	 at org.mineacademy.corearena.lib.fo.model.k.run(SourceFile:74)
	 at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84)
	 at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452)
----------------------------------------------------------------------------------------------
```

**Comment by JavaFactoryDev** [comment]
Please follow #275

**Comment by JavaFactoryDev** [comment]
Will be reopened when the user replies
