### ISSUE TITLE
1.16.1: ItemStack error when enabling the plugin

### ISSUE THREAD

**Issue by jiajunmao** [kangarko/CoreArena#322]
Hey I encountered a strange bug when enabling the plugin today, the error message did not make sense to me so I hope some people can give me a clue what's causing this.

```
[18:02:55 ERROR]: Error occurred while enabling CoreArena v2.7.3 (Is it up to date?)
org.mineacademy.corearena.short. .ah: Report / Value 'ItemStack{GOLD_INGOT x 1, UNSPECIFIC_META:{meta-type=UNSPECIFIC, display-name=§8> §6§lPlayer Spawnpoint §8<, lore=[, §6Left click §7a block to set, §
7a player spawnpoint§7. , , §7Break it to remove.], ItemFlags=[HIDE_ATTRIBUTES, HIDE_UNBREAKABLE], Unbreakable=true, internal=H4sIAAAAAAAAAONiYOBiEHDOL0p1LErNS4z3SyoJSUznYGBxT8xNZeB0TcksUfAsSc1lYAAABKsZB
yoAAAA=}}' is already in the list!
        at org.mineacademy.corearena.short. .y.a(SourceFile:77) ~[?:?]
        at org.mineacademy.corearena.lib.fo.collection.c.c(SourceFile:152) ~[?:?]
        at org.mineacademy.corearena.lib.fo.collection.c.b(SourceFile:132) ~[?:?]
        at org.mineacademy.corearena.CoreArenaPlugin.c(SourceFile:125) ~[?:?]
        at org.mineacademy.corearena.short. .aX.onEnable(SourceFile:233) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.1.jar:git-Paper-135]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.1.jar:git-Paper-135]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.1.jar:git-Paper-135]
        at com.rylinaux.plugman.util.PluginUtil.enable(PluginUtil.java:62) ~[?:?]
        at com.rylinaux.plugman.command.EnableCommand.execute(EnableCommand.java:127) ~[?:?]
        at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95) ~[?:?] 
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.1.jar:git-Paper-135]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.1.jar:git-Paper-135]
        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchCommand(CraftServer.java:794) ~[patched_1.16.1.jar:git-Paper-135]
        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchServerCommand(CraftServer.java:756) ~[patched_1.16.1.jar:git-Paper-135]
        at net.minecraft.server.v1_16_R1.DedicatedServer.handleCommandQueue(DedicatedServer.java:411) ~[patched_1.16.1.jar:git-Paper-135]
        at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:378) ~[patched_1.16.1.jar:git-Paper-135]
        at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1213) ~[patched_1.16.1.jar:git-Paper-135]
        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1001) ~[patched_1.16.1.jar:git-Paper-135]
        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-135]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

The server is running on Paper build 135 with FAWE snapshot 311 and Boss 3.8.2.

In addition to the previous bug, it appears that only vanilla spawneggs are working but not boss' spawneggs.

**Comment by kangarko** [comment]
Thanks, that should be patched on 2.7.4
