### ISSUE TITLE
1.16: (Fast)AsyncWorldEdit is broken, procedural damage severely limited

### ISSUE THREAD

**Issue by jiajunmao** [kangarko/CoreArena#328]
1) Error: something that looks like a thread deadlock between ca and async we/we

2) Behavior: when joining the end arena using /arena join, the server freezes for a period of time specified by we timeout (TPS < 15) in the config file and the arena is not joined due to we time out.

3) Tried: Since the size of the arena is moderate, copying pasting with awe would take about 15s to complete. Thus I have increased the timeout to 30s but the problem persists. I have also tried to replace awe/we with fawe and fawe seems to solve the problem.

4) Additional: I don't have the source code to CoreArena, so I can only guess that restoring snapshot is done by CoreArena calling the we API. However awe has its inherent property to not lag the server, what might be causing the server freeze when doing /arena join?

**Comment by LeehamElectronics** [comment]
Yes I can confirm that I have this issue as well.
Thanks

**Comment by jiajunmao** [comment]
Also when using fawe, everything seems fine with joining and loading the arena, however, when trying to create snapshots this error shows up in the console.

```
[16:44:22 INFO]: CoreArena 2.7.6 encountered an EOFException! Please check your error.log and report this issue with the information in that file.  [6/1953]│··············································
[16:44:22 INFO]: org.mineacademy.corearena.short. .al: Report / Failed to load INITIAL template for EndArena, see below and report (make sure you have the l│··············································
atest WorldEdit)                                                                                                                                            │··············································
[16:44:22 INFO]: at org.mineacademy.corearena.short. .ec.a(SourceFile:107)                                                                                  │··············································
[16:44:22 INFO]: at org.mineacademy.corearena.short. .ec.b(SourceFile:62)                                                                                   │··············································
[16:44:22 INFO]: at org.mineacademy.corearena.short. .ec.a(SourceFile:119)                                                                                  │··············································
[16:44:22 INFO]: at org.mineacademy.corearena.short. .fr.e(SourceFile:33)                                                                                   │··············································
[16:44:22 INFO]: at org.mineacademy.corearena.short. .eV$a.a(SourceFile:132)                                                                                │··············································
[16:44:22 INFO]: at org.mineacademy.corearena.short. .aD.a(SourceFile:775)                                                                                  │··············································
[16:44:22 INFO]: at org.mineacademy.corearena.short. .aE.onMenuClick(SourceFile:75)                                                                         │··············································
[16:44:22 INFO]: at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1361.execute(Unknown Source)                                 │··············································
[16:44:22 INFO]: at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)                                                                  │··············································
[16:44:22 INFO]: at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)                                                                 │··············································
[16:44:22 INFO]: at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)                                                              │··············································
[16:44:22 INFO]: at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)                                                           │··············································
[16:44:22 INFO]: at java.base/java.lang.Thread.run(Thread.java:834)                                                                                         │··············································
[16:44:22 INFO]: java.io.EOFException: Stream ended prematurely                                                                                             │··············································
[16:44:22 INFO]: at net.jpountz.lz4.LZ4BlockInputStream.readFully(LZ4BlockInputStream.java:212)                                                             │··············································
[16:44:22 INFO]: at net.jpountz.lz4.LZ4BlockInputStream.refill(LZ4BlockInputStream.java:142)                                                                │··············································
[16:44:22 INFO]: at net.jpountz.lz4.LZ4BlockInputStream.read(LZ4BlockInputStream.java:94)                                                                   │··············································
[16:44:22 INFO]: at com.sk89q.worldedit.extent.clipboard.io.SchematicReader.readCombined(SchematicReader.java:175)                                          │··············································
[16:44:22 INFO]: at com.sk89q.worldedit.extent.clipboard.io.SchematicReader.readwrite(SchematicReader.java:196)                                             │··············································
[16:44:22 INFO]: at com.sk89q.worldedit.extent.clipboard.io.SchematicReader.read(SchematicReader.java:268)                                                  │··············································
[16:44:22 INFO]: at com.sk89q.worldedit.extent.clipboard.io.ClipboardReader.read(ClipboardReader.java:59)                                                   │··············································
[16:44:22 INFO]: at com.sk89q.worldedit.extent.clipboard.io.ClipboardReader.read(ClipboardReader.java:46)                                                   │··············································
[16:44:22 INFO]: at org.mineacademy.corearena.short. .ec.a(SourceFile:95)                                                                                   │··············································
[16:44:22 INFO]: at org.mineacademy.corearena.short. .ec.b(SourceFile:62)                                                                                   │··············································
[16:44:22 INFO]: at org.mineacademy.corearena.short. .ec.a(SourceFile:119)                                                                                  │··············································
[16:44:22 INFO]: at org.mineacademy.corearena.short. .fr.e(SourceFile:33)                                                                                   │··············································
[16:44:22 INFO]: at org.mineacademy.corearena.short. .eV$a.a(SourceFile:132)                                                                                │··············································
[16:44:22 INFO]: at org.mineacademy.corearena.short. .aD.a(SourceFile:775)                                                                                  │··············································
[16:44:22 INFO]: at org.mineacademy.corearena.short. .aE.onMenuClick(SourceFile:75)                                                                         │··············································
[16:44:22 INFO]: at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1361.execute(Unknown Source)                                 │··············································
[16:44:22 INFO]: at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)                                                                  │··············································
[16:44:22 INFO]: at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)                                                                 │··············································
[16:44:22 INFO]: at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)                                                              │··············································
[16:44:22 INFO]: at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)                                                           │··············································
[16:44:22 INFO]: at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by kangarko** [comment]
Seems like both plugins are problematic with CA, I will look into creating our own system soon.

**Comment by LeehamElectronics** [comment]
> 
> 
> Lets continue here please: #328
> 
> Apparently AWE too has issues. I will prioritize this.

Hey thanks for the reply, yes you are correct, AWE causes a 'thread lock' and FAWE just does not work at all as we have previously discussed.

**Comment by kangarko** [comment]
Yeah that's unfortunate. I'll try to prioritize this.

**Comment by LeehamElectronics** [comment]
Is there anything I can do to help
Speed up this process? At the moment I can not use CoreArena at all until FAWE works with it, which is kind of sad because iv been hoping to reopen CoreArena on my main server for a while now. Is it possible that CoreArena will have its own world edit added to it without the thread lock?
Thanks

**Comment by kangarko** [comment]
For now you can use arenas without procedural damage on them. Apologies things take longer than expected, but I am not responsible for the other dev not fixing this earlier and trust me, writing our own schematic system is even more complex than the what WorldEdit offers - otherwise FAWE would probably have it long time ago.

**Comment by kangarko** [comment]
@LeehamElectronics @jiajunmao 

Unfortunately there's been weeks of struggle getting FAWE to work. Their support was great and helpful however the plugin has lots of bugs such as restoring maps produces 1 block offset, or even corrupts the edges completely, and lightning issues.

As such I rather decided to rewrite the current system using native WorldEdit and split restoring giant maps into chunks. See the upcoming plugin version and its changelog on Spigot for how it works ;) Hope you enjoy this!

**Comment by LeehamElectronics** [comment]
Thanks Matej! I will test it soon

**Comment by LeehamElectronics** [comment]
Works really well thanks Matej, still causes small TPS drops regardless of how low I set the options, but I'm guessing that's just world edit.

**Comment by kangarko** [comment]
Yep, we still need to place tens of thousands of blocks so it'll cause mini freezes during the arena load. You should only notice that when having an active pvp fight with anticheat on, but it should not interrupt the normal gameplay especially if you set the options low. That's a limitation of the load.
