### ISSUE TITLE
1.16.2: CoreArena not working

### ISSUE THREAD

**Issue by LeehamElectronics** [kangarko/CoreArena#335]
I am using the latest 1.16.2 PaperMC, most things in CoreArena is working however when I click on the save snapshot button in ma menu it fails and generates this error in the console:
```
[11:43:27 INFO]: mail2002 issued server command: /ma menu
[11:43:35 INFO]: CoreArena 2.7.8 encountered an EOFException! Please check your error.log and report this issue with the information in that file.
[11:43:35 INFO]: org.mineacademy.corearena.short. .al: Report / Failed to load INITIAL template for SandCastle, see below and report (make sure you have the latest WorldEdit)
[11:43:35 INFO]: at org.mineacademy.corearena.short. .ed.a(SourceFile:107)
[11:43:35 INFO]: at org.mineacademy.corearena.short. .ed.b(SourceFile:62)
[11:43:35 INFO]: at org.mineacademy.corearena.short. .ed.a(SourceFile:119)
[11:43:35 INFO]: at org.mineacademy.corearena.short. .fs.e(SourceFile:33)
[11:43:35 INFO]: at org.mineacademy.corearena.short. .eW$a.a(SourceFile:132)
[11:43:35 INFO]: at org.mineacademy.corearena.short. .aD.a(SourceFile:775)
[11:43:35 INFO]: at org.mineacademy.corearena.short. .aE.onMenuClick(SourceFile:75)
[11:43:35 INFO]: at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor862.execute(Unknown Source)
[11:43:35 INFO]: at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[11:43:35 INFO]: at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[11:43:35 INFO]: at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[11:43:35 INFO]: at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
[11:43:35 INFO]: at java.lang.Thread.run(Unknown Source)
[11:43:35 INFO]: java.io.EOFException: Stream ended prematurely
[11:43:35 INFO]: at net.jpountz.lz4.LZ4BlockInputStream.readFully(LZ4BlockInputStream.java:212)
[11:43:35 INFO]: at net.jpountz.lz4.LZ4BlockInputStream.refill(LZ4BlockInputStream.java:142)
[11:43:35 INFO]: at net.jpountz.lz4.LZ4BlockInputStream.read(LZ4BlockInputStream.java:94)
[11:43:35 INFO]: at com.sk89q.worldedit.extent.clipboard.io.SchematicReader.readCombined(SchematicReader.java:175)
[11:43:35 INFO]: at com.sk89q.worldedit.extent.clipboard.io.SchematicReader.readwrite(SchematicReader.java:196)
[11:43:35 INFO]: at com.sk89q.worldedit.extent.clipboard.io.SchematicReader.read(SchematicReader.java:268)
[11:43:35 INFO]: at com.sk89q.worldedit.extent.clipboard.io.ClipboardReader.read(ClipboardReader.java:59)
[11:43:35 INFO]: at com.sk89q.worldedit.extent.clipboard.io.ClipboardReader.read(ClipboardReader.java:46)
[11:43:35 INFO]: at org.mineacademy.corearena.short. .ed.a(SourceFile:95)
[11:43:35 INFO]: at org.mineacademy.corearena.short. .ed.b(SourceFile:62)
[11:43:35 INFO]: at org.mineacademy.corearena.short. .ed.a(SourceFile:119)
[11:43:35 INFO]: at org.mineacademy.corearena.short. .fs.e(SourceFile:33)
[11:43:35 INFO]: at org.mineacademy.corearena.short. .eW$a.a(SourceFile:132)
[11:43:35 INFO]: at org.mineacademy.corearena.short. .aD.a(SourceFile:775)
[11:43:35 INFO]: at org.mineacademy.corearena.short. .aE.onMenuClick(SourceFile:75)
[11:43:35 INFO]: at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor862.execute(Unknown Source)
[11:43:35 INFO]: at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[11:43:35 INFO]: at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[11:43:35 INFO]: at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[11:43:35 INFO]: at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
[11:43:35 INFO]: at java.lang.Thread.run(Unknown Source)
[11:43:35 INFO]: !-----------------------------------------------------!
[11:43:35 INFO]: Error clicking in menu eW{}
[11:43:35 INFO]: !-----------------------------------------------------!
```
![image](https://user-images.githubusercontent.com/51737378/91374164-ec74ce00-e85a-11ea-961f-bcbb332ccf9c.png)

I am using the latest version of Fast AsyncWorldEdit which works fine everywhere else on my server, it's only CoreArena that is not working with snapshots.
Thanks for your help.

**Comment by LeehamElectronics** [comment]
I setup a test server with the latest CoreArena and FAWE and its still the same error message:
```
[13:13:32 INFO]: mail2002 issued server command: /ma menu
[13:13:54 INFO]: CoreArena 2.7.8 encountered an EOFException! Please check your error.log and report this issue with the information in that file.
[13:13:54 INFO]: org.mineacademy.corearena.short. .al: Report / Failed to load INITIAL template for test, see below and report (make sure you have the latest WorldEdit)
[13:13:54 INFO]: at org.mineacademy.corearena.short. .ed.a(SourceFile:107)
[13:13:54 INFO]: at org.mineacademy.corearena.short. .ed.b(SourceFile:62)
[13:13:54 INFO]: at org.mineacademy.corearena.short. .ed.a(SourceFile:119)
[13:13:54 INFO]: at org.mineacademy.corearena.short. .fs.e(SourceFile:33)
[13:13:54 INFO]: at org.mineacademy.corearena.short. .eW$a.a(SourceFile:132)
[13:13:54 INFO]: at org.mineacademy.corearena.short. .aD.a(SourceFile:775)
[13:13:54 INFO]: at org.mineacademy.corearena.short. .aE.onMenuClick(SourceFile:75)
[13:13:54 INFO]: at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor480.execute(Unknown Source)
[13:13:54 INFO]: at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[13:13:54 INFO]: at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[13:13:54 INFO]: at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[13:13:54 INFO]: at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
[13:13:54 INFO]: at java.lang.Thread.run(Unknown Source)
[13:13:54 INFO]: java.io.EOFException: Stream ended prematurely
[13:13:54 INFO]: at net.jpountz.lz4.LZ4BlockInputStream.readFully(LZ4BlockInputStream.java:212)
[13:13:54 INFO]: at net.jpountz.lz4.LZ4BlockInputStream.refill(LZ4BlockInputStream.java:142)
[13:13:54 INFO]: at net.jpountz.lz4.LZ4BlockInputStream.read(LZ4BlockInputStream.java:94)
[13:13:54 INFO]: at com.sk89q.worldedit.extent.clipboard.io.SchematicReader.readCombined(SchematicReader.java:175)
[13:13:54 INFO]: at com.sk89q.worldedit.extent.clipboard.io.SchematicReader.readwrite(SchematicReader.java:196)
[13:13:54 INFO]: at com.sk89q.worldedit.extent.clipboard.io.SchematicReader.read(SchematicReader.java:268)
[13:13:54 INFO]: at com.sk89q.worldedit.extent.clipboard.io.ClipboardReader.read(ClipboardReader.java:59)
[13:13:54 INFO]: at com.sk89q.worldedit.extent.clipboard.io.ClipboardReader.read(ClipboardReader.java:46)
[13:13:54 INFO]: at org.mineacademy.corearena.short. .ed.a(SourceFile:95)
[13:13:54 INFO]: at org.mineacademy.corearena.short. .ed.b(SourceFile:62)
[13:13:54 INFO]: at org.mineacademy.corearena.short. .ed.a(SourceFile:119)
[13:13:54 INFO]: at org.mineacademy.corearena.short. .fs.e(SourceFile:33)
[13:13:54 INFO]: at org.mineacademy.corearena.short. .eW$a.a(SourceFile:132)
[13:13:54 INFO]: at org.mineacademy.corearena.short. .aD.a(SourceFile:775)
[13:13:54 INFO]: at org.mineacademy.corearena.short. .aE.onMenuClick(SourceFile:75)
[13:13:54 INFO]: at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor480.execute(Unknown Source)
[13:13:54 INFO]: at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[13:13:54 INFO]: at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[13:13:54 INFO]: at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[13:13:54 INFO]: at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
[13:13:54 INFO]: at java.lang.Thread.run(Unknown Source)
[13:13:54 INFO]: !-----------------------------------------------------!
[13:13:54 INFO]: Error clicking in menu eW{}
[13:13:54 INFO]: !-----------------------------------------------------!
```

**Comment by kangarko** [comment]
Sadly, this might be a problem within FAWE. Does it happen on vanilla WorldEdit? They did a lot of fixing recently, you can test using the very latest dev build from here: https://builds.enginehub.org/job/worldedit?branch=master

**Comment by Equity7** [comment]
Just in case I can help...I am running Paper 1.16.2 with WorldEdit (not FAWE) and it works fine without any console errors.

**Comment by LeehamElectronics** [comment]
Yeh I really need to use FAWE for CoreArena procedural damage arenas otherwise there is a massive thread lock which stops the server completely when joining a large arena. Matej already said that he will be re writing CoreArena to fix this issue but in the mean time I would have liked to use FAWE for CoreArena however even that's not working. I'm using the latest dev build of FAWE which works for everything other than CoreArena so hopefully Matej can quickly patch this so I can keep using CoreArena without my servers crashing. Thanks for the comment but yes I have already tried just using WE on it's on, it does work, but it does cause a thread lock on large maps making my server unplayable.

**Comment by LeehamElectronics** [comment]
I think I may know what the issue with CoreArena and FAWE is, when clicking load arena snapshot it generates an error which might be because CoreArena can not find the schematics in the typical world edit folder. I think this is because FAWE stores schematics in a different folder now, could you possibly try and see if you can reproduce the issue Matej? I think the issue may be a simple as a changing a files directory. I will try and manually change the schematics directory later today and I'll let you know if it works.

**Comment by LeehamElectronics** [comment]
Still not working with the latest version of FAWE, any chance we could get that working?
Thanks

**Comment by kangarko** [comment]
Thanks, yes we are working on it but I had to leave around 10 days ago and returned yesterday. Will try to get this solved in 1-2 days.

**Comment by kangarko** [comment]
I fixed the first half of the problem where we would no longer detect FAWE correctly, since they now attribute themselves as FastAsyncWorldEdit (previously only WorldEdit in /plugins).

However, loading schematics is still broken with a reason unknown to me, so I opened a ticket on their side:
https://github.com/IntellectualSites/FastAsyncWorldEdit/issues/605

Just to clarify this problem is isolated to FAWE only. Vanilla WorldEdit is unaffected: https://i.imgur.com/pmlA6Wp.gif

I understand how frustrating this can be so I am willing to completely abandon using WorldEdit and implement some sort of a custom storage system (which will be limited since I am not as advanced in saving tile metadata such as chest contents etc as they are) but it will work async and won't lag arenas.

**Comment by LeehamElectronics** [comment]
> 
> 
> I fixed the first half of the problem where we would no longer detect FAWE correctly, since they now attribute themselves as FastAsyncWorldEdit (previously only WorldEdit in /plugins).
> 
> However, loading schematics is still broken with a reason unknown to me, so I opened a ticket on their side:
> [IntellectualSites/FastAsyncWorldEdit#605](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues/605)
> 
> Just to clarify this problem is isolated to FAWE only. Vanilla WorldEdit is unaffected: https://i.imgur.com/pmlA6Wp.gif
> 
> I understand how frustrating this can be so I am willing to completely abandon using WorldEdit and implement some sort of a custom storage system (which will be limited since I am not as advanced in saving tile metadata such as chest contents etc as they are) but it will work async and won't lag arenas.

I also messaged them on Discord about this, I think the issue may be that FAWE saves schematics in a different folder located in main server-folder/schematics/userUUID/schem   and as a result CoreArena can not save the schematic directory to the typical plugins/worldedit/schematics folder. Do you think it may just be a file directory issue? I'm just guessing. 
I think there may also be a difference between .schem and .schematic files but I am not too sure about that.
Thanks, let me know if this helped.

**Comment by aurorasmiles** [comment]
> I also messaged them on Discord about this, I think the issue may be that FAWE saves schematics in a different folder located in main server-folder/schematics/schem-name

That was a bug in FAWE that I have fixed a few days ago

**Comment by kangarko** [comment]
I have fixed the issue of the wrong folder and starting the next Boss version, we will look for schematics in FastAsyncWorldEdit/ folder. That means you'd have to recreate the snapshots again. However, from my testing this will still throw errors when loading the paste. I opened a ticket on their side.

**Comment by LeehamElectronics** [comment]
Looks like they might take a while to fix the FAWE issue on their side, any ETA on when CoreArena will have its own WorldEdit built into it?
Thanks

**Comment by kangarko** [comment]
I understand, you can actually disable procedural damage for arenas and play them without them for now.

No ETA yet because ChatControl had some other issues I had to deal with, being a single dev for five plugins is fun haha, but I'll try to do it in the coming weeks.

**Comment by kangarko** [comment]
@LeehamElectronics so you are still on 1.16.**2** ? Did I ever suggested using AWE instead of FAWE (can't remember but probably did) -- what about this?

**Comment by kangarko** [comment]
Lets continue here please: https://github.com/kangarko/CoreArena/issues/328

Apparently AWE too has issues. I will prioritize this.
