### ISSUE TITLE
1.6.3: Unexpected String Format preventing use of arena tools

### ISSUE THREAD

**Issue by Griskard** [kangarko/CoreArena#360]
When I attempt to use the arena tools to define an arena I get an error log about the string being wrong?

------------------------------------[ 17.10.2020 13:36:18 ]-----------------------------------
CoreArena 2.7.17 encountered an aq
Running CraftBukkit 1.16.3-R0.1-SNAPSHOT and Java 1.8.0_262
Plugins: TitanPermissions v1.0-SNAPSHOT, mcMMO v2.1.148, TownyMenu v1.1.13, Vault v1.7.3-b131, ProtocolLib v4.6.0-SNAPSHOT-b480, WorldEdit v7.2.0-rc-01+81f978e, Essentials v2.18.1.0, EssentialsProtect v2.18.1.0, AdvancedEnchantments v8.0.0-Pre8.2, EssentialsChat v2.18.1.0, EssentialsGeoIP v2.18.1.0, AdvancedSpawners v2.6.8, Towny v0.96.2.0, CraftBook v3.10.2;21180b0, UltimateShops v2.0.7, EssentialsSpawn v2.18.1.0, TownyChat v0.72, EssentialsXMPP v2.18.1.0, TownyNameUpdater v4.0, TheNewEconomy v0.1.1.12, ChatControl v5.9.0, Boss v3.8.14, CoreArena v2.7.17
----------------------------------------------------------------------------------------------

More Information: 
Expected location (String) but got String: Sanctuary Alpha 257 103 -724
aq Report: Expected location (String) but got String: Sanctuary Alpha 257 103 -724
	 at org.mineacademy.corearena.i.z.a(SourceFile:81)
	 at org.mineacademy.corearena.i.v.b(SourceFile:354)
	 at org.mineacademy.corearena.i.v.deserialize(SourceFile:286)
	 at org.mineacademy.corearena.i.v.deserialize(SourceFile:202)
	 at org.mineacademy.corearena.i.cs.a(SourceFile:643)
	 at org.mineacademy.corearena.i.cs.a(SourceFile:619)
	 at org.mineacademy.corearena.i.cs.o(SourceFile:883)
	 at org.mineacademy.corearena.i.dT.B(SourceFile:106)
	 at org.mineacademy.corearena.i.dT.a(SourceFile:216)
	 at org.mineacademy.corearena.i.fV.a(SourceFile:54)
	 at org.mineacademy.corearena.i.gz.a(SourceFile:93)
	 at org.mineacademy.corearena.i.ba.onToolClick(SourceFile:79)
	 at java.lang.reflect.Method.invoke(Method.java:498)
	 at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315)
	 at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
	 at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589)
	 at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576)
	 at org.bukkit.craftbukkit.v1_16_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:483)
	 at org.bukkit.craftbukkit.v1_16_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:450)
----------------------------------------------------------------------------------------------

**Comment by kangarko** [comment]
Worlds do not support spaces: "Sanctuary Alpha", rename your world to Sanctuary_Alpha.
