### ISSUE TITLE
1.15.2: FAWE Not supported yet FAWE classes are used?

### ISSUE THREAD

**Issue by eDexiam** [kangarko/CoreArena#414]
This is in relation of #406, FAWE is not supported however in version 2.8.7 (which is the latest at the time of writing) it is referencing FAWE classes and causing warnings in my console. I've switched from using FAWE to the "normal" WorldEdit after noticing snapshot issues.

```[16:51:51 WARN]: [CoreArena] Task #70334 for CoreArena v2.8.7 generated an exception
java.lang.NoClassDefFoundError: com/boydti/fawe/object/RelightMode
        at org.mineacademy.game.impl.SimpleSnapshotWorldEdit$1.onFinish(SimpleSnapshotWorldEdit.java:239) ~[?:?]
        at org.mineacademy.corearena.lib.fo.model.ChunkedTask.lambda$startChain$0(ChunkedTask.java:63) ~[?:?]
        at org.mineacademy.corearena.lib.fo.remain.CompRunnable$SafeRunnable.run(CompRunnable.java:68) ~[?:?]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.15.2.jar:git-Paper-391]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.15.2.jar:git-Paper-391]
        at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1265) ~[patched_1.15.2.jar:git-Paper-391]
        at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:431) ~[patched_1.15.2.jar:git-Paper-391]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1182) ~[patched_1.15.2.jar:git-Paper-391]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:971) ~[patched_1.15.2.jar:git-Paper-391]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ClassNotFoundException: com.boydti.fawe.object.RelightMode
        at java.net.URLClassLoader.findClass(URLClassLoader.java:471) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:171) ~[patched_1.15.2.jar:git-Paper-391]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[patched_1.15.2.jar:git-Paper-391]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:589) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
        ... 10 more
```

**Comment by kangarko** [comment]
Yeah we can't guarantee FAWE will work. There's a hook but that was pain in the butt for months so eventually I just stopped supporting this. We only support vanilla WordEdit.
