### ISSUE TITLE
Error when reloading plugin / joining arena

### ISSUE THREAD

**Issue by British89** [kangarko/CoreArena#418]
When i try to reload with /ma reload i see this in chat
Arena// Oups! Reloading failed due to an error! See console for more information,
Error: Health must be between 0 and 16 but was 18 (attribute base valueL 18, player: British89)
```
[code]28.03 16:59:52 [Server] INFO !-----------------------------------------------------!
28.03 16:59:52 [Server] INFO Error while joining British89 to Desert
28.03 16:59:52 [Server] INFO Arena has been stopped for safety.
28.03 16:59:52 [Server] INFO !-----------------------------------------------------!
28.03 16:59:52 [Server] INFO GG! The game in Desert has finished!
28.03 16:59:52 [Server] WARN at org.bukkit.craftbukkit.v1_16_R3.entity.CraftLivingEntity.setHealth(CraftLivingEntity.java:117)
28.03 16:59:52 [Server] WARN at org.mineacademy.corearena.lib.fo.PlayerUtil.normalize(PlayerUtil.java:317)
28.03 16:59:52 [Server] WARN at org.mineacademy.corearena.lib.fo.PlayerUtil.normalize(PlayerUtil.java:290)
28.03 16:59:52 [Server] WARN at org.mineacademy.game.impl.arena.SimpleArena.handlePlayerLeave0(SimpleArena.java:586)
28.03 16:59:52 [Server] WARN at org.mineacademy.game.impl.arena.SimpleArena.handlePlayerLeave(SimpleArena.java:546)
28.03 16:59:52 [Server] WARN at org.mineacademy.game.impl.arena.SimpleArena.removeAllPlayers(SimpleArena.java:529)
28.03 16:59:52 [Server] WARN at org.mineacademy.game.impl.arena.SimpleArena.doStop(SimpleArena.java:473)
28.03 16:59:52 [Server] WARN at org.mineacademy.game.impl.arena.SimpleArena.stopArena(SimpleArena.java:415)
28.03 16:59:52 [Server] WARN at org.mineacademy.game.impl.arena.SimpleArena.joinPlayer(SimpleArena.java:143)
28.03 16:59:52 [Server] WARN at org.mineacademy.game.command.JoinCommand.onCommand(JoinCommand.java:39)
28.03 16:59:52 [Server] WARN at org.mineacademy.corearena.lib.fo.command.SimpleCommand.execute(SimpleCommand.java:390)
28.03 16:59:52 [Server] WARN at org.mineacademy.corearena.lib.fo.command.SimpleCommandGroup$MainCommand.onCommand(SimpleCommandGroup.java:374)
28.03 16:59:52 [Server] WARN at org.mineacademy.corearena.lib.fo.command.SimpleCommand.execute(SimpleCommand.java:390)
28.03 16:59:52 [Server] WARN at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
28.03 16:59:52 [Server] WARN at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:810)
28.03 16:59:52 [Server] WARN at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2023)[/code]
```

**Comment by kangarko** [comment]
Thanks, should be solved in the next version
