### ISSUE TITLE
1.16.5 & 1.17.1: Rewards menu not opening in new CoreArena Version

### ISSUE THREAD

**Issue by nebula3077** [kangarko/CoreArena#427]
It seems as though the new version of the plugin broke the rewards menu. I'm getting the following error when running /arena rewards:

**In Game Error:** "Oops! The command failed :( Check the console and report the error. "

**Console Error:**
```
Issued server command: /arena rewards
[20:04:47 INFO]: CoreArena 2.9.2 encountered a FoException! Please check your error.log and report this issue with the information in that file.
[20:04:47 INFO]: org.mineacademy.corearena.lib.fo.exception.FoException: Report: One menu instance can be shown to one player only, MenuRewards{} is already visible for CraftPlayer{name=PlayerUsernameRedacted}
[20:04:47 INFO]: at org.mineacademy.corearena.lib.fo.Valid.checkBoolean(Valid.java:81)
[20:04:47 INFO]: at org.mineacademy.corearena.lib.fo.menu.Menu.displayTo(Menu.java:379)
[20:04:47 INFO]: at org.mineacademy.game.menu.MenuRewards.showRewardsMenu(MenuRewards.java:66)
[20:04:47 INFO]: at org.mineacademy.game.command.RewardsCommand.onCommand(RewardsCommand.java:28)
[20:04:47 INFO]: at org.mineacademy.corearena.lib.fo.command.SimpleCommand.execute(SimpleCommand.java:404)
[20:04:47 INFO]: at org.mineacademy.corearena.lib.fo.command.SimpleCommandGroup$MainCommand.onCommand(SimpleCommandGroup.java:374)
[20:04:47 INFO]: at org.mineacademy.corearena.lib.fo.command.SimpleCommand.execute(SimpleCommand.java:404)
[20:04:47 INFO]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172)
[20:04:47 INFO]: at java.base/java.lang.Thread.run(Thread.java:834)
[20:04:47 INFO]: !-----------------------------------------------------!
[20:04:47 INFO]: Failed to execute command /arena rewards
[20:04:47 INFO]: !-----------------------------------------------------!
[20:04:47 INFO]: [CoreArena 2.9.2] Command /arena rewards took 21.22 ms
```

Might have something to do with the Nashorn library change and removal. Not sure though as I didn't look into this any further. I find the issue resolves itself when switching back over to 2.9.1.

**Broken Plugin Versions:** 2.9.3, 2.9.2
**Working Versions:** 2.9.1 and anything earlier

This issue can be reproduced on a fresh install of 1.16.5 and 1.17.1 with no plugins. I've tried with and without the NashornPlus library but it doesn't change anything.

**Comment by kangarko** [comment]
Thanks, fixed!
