### ISSUE TITLE
NPE - Arena Stops at end of countdown - Paper 1.18.1 number 95

### ISSUE THREAD

**Issue by cobrex1** [kangarko/CoreArena#434]
I updated both boss (old 3.10.9) and core arena (old 3.0.6) to the most recent versions 4.1.4 and 3.0.7.

On starting an arena, the count-down runs and when it gets to zero, the arena stops and I am sent back to the nominated lobby position with the message to review the error logs. The error message is as follows:

------------------------------------[ 25.12.2021 09:46:05 ]-----------------------------------
CoreArena 3.0.7 encountered a NullPointerException
Running Paper 1.18.1-R0.1-SNAPSHOT and Java 17.0.1
Plugins: LoginRewards v1.0, Chunky v1.2.153, PlaceholderAPI v2.11.0, DeluxeCommands v1.12-DEV, CommandToItem v${version}, HolographicDisplays v3.0.0-SNAPSHOT-b185, PyroLib v1.0.0, VoteParty v2.30, VillagerModifications v1.5.0, MC-Cron v1.9.1, DeathMessages v1.0, ViaVersion v4.1.2-SNAPSHOT, NBTAPI v2.9.0-SNAPSHOT, ViaBackwards v4.1.2-SNAPSHOT, LuckPerms v5.3.89, GBooster v1.2.4, VoidGen v2.1.3, AnimatedScoreboard v0.2.5, SirBlobmanCore v2.3.4, ArmorStandEditor v1.18.1-32, spark v1.6.4, JetsAntiAFKPro v3.4.7, ProtocolLib v4.8.0-SNAPSHOT-b539, AdvancedPortals v0.8.0, SayWelcome v1.1.1, Vault v1.7.3-b131, TokenManager v3.2.6, ViaRewind v2.0.2, ClientDetector v2.3.1, HolographicExtension v1.10.11, CrazyCrates v1.10.1, MoneyPouch v3.6.1, Item2Chat v6.5.0, PlayerVaults v4.2.5, boosCooldowns v3.17.1, WorldEdit v7.2.8+6008-1246d61, Essentials v2.19.2, PyroMining v4.3.6, HeadDatabase v4.15.1, Multiverse-Core v4.3.1-b861, AsyncWorldEdit v3.9.3, CrazyAuctions v1.2.17-SNAPSHOT-Build#41, DeluxeMenus v1.13.4-Release, Lottery v1.4-SNAPSHOT, WorldGuard v7.0.6+1cff55f, Images v2.2.4, EssentialsSpawn v2.19.2, WorldGuardExtraFlags v4.1.4, TempFly v3.1.0, Guilds v3.5.6.3-DEV, PyroFishingPro v4.6.2, ServerTutorialPlus v1.23.3, Citizens v2.0.29-SNAPSHOT (build 2420), mcMMO v2.1.206, ItemJoin v5.2.3-RELEASE-b789, GriefPrevention v16.17.1-42-g3562a23-dirty, ChestShop v3.12.1-SNAPSHOT (build 334), Elevators v4.0.6, CrazyEnvoy v1.3.11-Build#70, Boss v4.1.4, NametagEdit v4.5.2, SuperTrailsPro vv1.2.18, LeaderHeadsRevamped v4.0.6, ClaimFly v1.2.6, Quests v4.1.3-b287, GriefpreventionAddon v0.1-SNAPSHOT, CoreArena v3.0.7, Wild v4.4.4-SNAPSHOT, PremiumVanish v2.7.8, AdvancedEnchantments v8.7.24, CMILib v1.1.0.4, MorphRedeem v1.2.3, MobFarmManager v2.0.1.0, CombatLogX v10.4.2.4
----------------------------------------------------------------------------------------------

More Information: 
Error while spawning mobs in Tutorial1
%error
Stopping arena for safety.
NullPointerException Cannot invoke "org.mineacademy.boss.lib.model.Tuple.getKey()" because "spawned" is null
	 at CoreArena-3.0.7.jar//org.mineacademy.game.hook.BossHook.tryBossSpawn(CoreHookManager.java:117)
	 at CoreArena-3.0.7.jar//org.mineacademy.game.hook.CoreHookManager.tryBOSSSpawn(CoreHookManager.java:56)
	 at CoreArena-3.0.7.jar//org.mineacademy.game.impl.SimplePhaseIncremental.spawnMobs(SimplePhaseIncremental.java:467)
	 at CoreArena-3.0.7.jar//org.mineacademy.game.impl.SimplePhaseIncremental.startTimer(SimplePhaseIncremental.java:551)
	 at CoreArena-3.0.7.jar//org.mineacademy.game.impl.arena.SimpleArena.doStart(SimpleArena.java:383)
	 at CoreArena-3.0.7.jar//org.mineacademy.game.impl.arena.SimpleArena.startArena(SimpleArena.java:320)
	 at CoreArena-3.0.7.jar//org.mineacademy.game.countdown.LaunchCountdown.onEnd(LaunchCountdown.java:25)
	 at CoreArena-3.0.7.jar//org.mineacademy.corearena.lib.fo.model.Countdown.run(Countdown.java:89)
	 at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101)
	 at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
----------------------------------------------------------------------------------------------

Looking forward to hearing from you.

**Comment by kangarko** [comment]
Thanks, will be fixed!
