### ISSUE TITLE
1.18.2: Mythic Mobs eggs turning into sheep eggs

### ISSUE THREAD

**Issue by BeepSterr** [kangarko/CoreArena#451]
So I've been making some custom mobs with Mythic Mobs for my arena, But putting them in seems to not save them properly.
The only output in the console i'm getting is the following:

```[00:11:35 INFO]: [CoreArena] Warning: Detected invalid custom egg in one of your spawners, replacing with sheep.
[00:11:35 INFO]: [CoreArena] Warning: Detected invalid custom egg in one of your spawners, replacing with sheep.
[00:11:35 INFO]: [CoreArena] Warning: Detected invalid custom egg in one of your spawners, replacing with sheep.
[00:11:37 INFO]: [CoreArena] Warning: Detected invalid custom egg in one of your spawners, replacing with sheep.
[00:11:37 INFO]: [CoreArena] Warning: Detected invalid custom egg in one of your spawners, replacing with sheep.
[00:11:37 INFO]: [CoreArena] Warning: Detected invalid custom egg in one of your spawners, replacing with sheep.
```

CoreArena version: 3.1.6
Mythic Mobs version: 5.0.2 (a86da3b0)
Server version: git-Paper-268 (MC 1.18.2)

Is there anything I should set up for getting Mythic Mobs support?

**Comment by kangarko** [comment]
Thank you I will patch this in the next release!

**Comment by BeepSterr** [comment]
Hey, Thanks for getting to this so quickly.. However with the new release, only pigs are spawning... The following errors get thrown in the console when the arena with MythicMob mobs is active.

```[23:04:19 INFO]: [CoreArena] The game in The_End has begun (1/12)!
[23:04:36 ERROR]: Could not pass event EntityDeathEvent to CoreArena v3.1.7
java.lang.NoClassDefFoundError: io/lumine/xikage/mythicmobs/MythicMobs
at org.mineacademy.game.hook.MythicMobsHook.getBossName(CoreHookManager.java:91) ~[CoreArena-3.1.7.jar:?]
at org.mineacademy.game.hook.CoreHookManager.getBossName(CoreHookManager.java:66) ~[CoreArena-3.1.7.jar:?]
at org.mineacademy.game.impl.SimpleSettings.getExpFor(SimpleSettings.java:350) ~[CoreArena-3.1.7.jar:?]
at org.mineacademy.game.impl.arena.FeatureArena.onEntityDeath(FeatureArena.java:266) ~[CoreArena-3.1.7.jar:?]
at org.mineacademy.game.listener.InArenaListener.onEntityDeath(InArenaListener.java:570) ~[CoreArena-3.1.7.jar:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor667.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:git-Purpur-1598]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:631) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.v1_18_R2.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:887) ~[purpur-1.18.2.jar:git-Purpur-1598]
at net.minecraft.world.entity.LivingEntity.dropAllDeathLoot(LivingEntity.java:1781) ~[?:?]
at net.minecraft.world.entity.LivingEntity.die(LivingEntity.java:1677) ~[?:?]
at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1492) ~[?:?]
at net.minecraft.world.entity.player.Player.attack(Player.java:1319) ~[?:?]
at net.minecraft.server.level.ServerPlayer.attack(ServerPlayer.java:2142) ~[?:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl$6.a(ServerGamePacketListenerImpl.java:2626) ~[?:?]
at net.minecraft.network.protocol.game.ServerboundInteractPacket$1.dispatch(ServerboundInteractPacket.java:24) ~[?:?]
at net.minecraft.network.protocol.game.ServerboundInteractPacket.dispatch(ServerboundInteractPacket.java:80) ~[?:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl.handleInteract(ServerGamePacketListenerImpl.java:2551) ~[?:?]
at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:67) ~[?:?]
at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:12) ~[?:?]
at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.18.2.jar:git-Purpur-1598]
at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1426) ~[purpur-1.18.2.jar:git-Purpur-1598]
at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188) ~[purpur-1.18.2.jar:git-Purpur-1598]
at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1403) ~[purpur-1.18.2.jar:git-Purpur-1598]
at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1396) ~[purpur-1.18.2.jar:git-Purpur-1598]
at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1374) ~[purpur-1.18.2.jar:git-Purpur-1598]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1256) ~[purpur-1.18.2.jar:git-Purpur-1598]
at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:320) ~[purpur-1.18.2.jar:git-Purpur-1598]
at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: io.lumine.xikage.mythicmobs.MythicMobs
at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:153) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:105) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
... 36 more```

CoreArena version: 3.1.7
Mythic Mobs version: 5.0.2 (a86da3b0)
Server Version: git-Paper-268 (MC1.18.2)

**Comment by kangarko** [comment]
Thanks, will be solved!Thanks, will be solved!
