### ISSUE TITLE
1.18.2: Localization error for inbuilt file.

### ISSUE THREAD

**Issue by TechRoot** [kangarko/CoreArena#465]
Plugin fails to reload due to this error happening on /ca reload when you use 'locale' key set to 'es' in settings.

```
[13:21:06 ERROR]: CoreArena 3.2.5 encountered a FoException! Please check your error.log and report this issue with the information in that file.
[13:21:06 INFO]: Arena // Oups! La recarga falló debido a un error! Consulte la consola para obtener más información. Error: Report: Inbuilt config messages_es.yml lacks key at "Commands.Find.Wrong_Syntax". Is it outdated?
[13:21:06 WARN]: org.mineacademy.corearena.lib.fo.exception.FoException: Report: Inbuilt config messages_es.yml lacks key at "Commands.Find.Wrong_Syntax". Is it outdated?
[13:21:06 WARN]:        at CoreArena-3.2.5.jar//org.mineacademy.corearena.lib.fo.Valid.checkNotNull(Valid.java:61)
[13:21:06 WARN]:        at CoreArena-3.2.5.jar//org.mineacademy.corearena.lib.fo.settings.FileConfig.copyDefault(FileConfig.java:223)
[13:21:06 WARN]:        at CoreArena-3.2.5.jar//org.mineacademy.corearena.lib.fo.settings.FileConfig.get(FileConfig.java:191)
[13:21:06 WARN]:        at CoreArena-3.2.5.jar//org.mineacademy.corearena.lib.fo.settings.FileConfig.getObject(FileConfig.java:719)
[13:21:06 WARN]:        at CoreArena-3.2.5.jar//org.mineacademy.corearena.lib.fo.settings.FileConfig.getString(FileConfig.java:274)
[13:21:06 WARN]:        at CoreArena-3.2.5.jar//org.mineacademy.corearena.lib.fo.settings.FileConfig.getString(FileConfig.java:260)
[13:21:06 WARN]:        at CoreArena-3.2.5.jar//org.mineacademy.corearena.lib.fo.settings.YamlStaticConfig.getString(YamlStaticConfig.java:319)
[13:21:06 WARN]:        at CoreArena-3.2.5.jar//org.mineacademy.game.settings.Localization.access$11500(Localization.java:15)
[13:21:06 WARN]:        at CoreArena-3.2.5.jar//org.mineacademy.game.settings.Localization$Commands$Find.init(Localization.java:503)
[13:21:06 WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[13:21:06 WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[13:21:06 WARN]:        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[13:21:06 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[13:21:06 WARN]:        at CoreArena-3.2.5.jar//org.mineacademy.corearena.lib.fo.settings.YamlStaticConfig.invokeMethodsIn(YamlStaticConfig.java:206)
[13:21:06 WARN]:        at CoreArena-3.2.5.jar//org.mineacademy.corearena.lib.fo.settings.YamlStaticConfig.invokeAll(YamlStaticConfig.java:183)
[13:21:06 WARN]:        at CoreArena-3.2.5.jar//org.mineacademy.corearena.lib.fo.settings.YamlStaticConfig.loadViaReflection(YamlStaticConfig.java:161)
[13:21:06 WARN]:        at CoreArena-3.2.5.jar//org.mineacademy.corearena.lib.fo.settings.YamlStaticConfig.access$000(YamlStaticConfig.java:34)
[13:21:06 WARN]:        at CoreArena-3.2.5.jar//org.mineacademy.corearena.lib.fo.settings.YamlStaticConfig$1.onLoad(YamlStaticConfig.java:70)
[13:21:06 WARN]:        at CoreArena-3.2.5.jar//org.mineacademy.corearena.lib.fo.settings.FileConfig.load(FileConfig.java:1173)
[13:21:06 WARN]:        at CoreArena-3.2.5.jar//org.mineacademy.corearena.lib.fo.settings.YamlConfig.loadConfiguration(YamlConfig.java:173)
[13:21:06 WARN]:        at CoreArena-3.2.5.jar//org.mineacademy.corearena.lib.fo.settings.YamlStaticConfig.loadConfiguration(YamlStaticConfig.java:241)
[13:21:06 WARN]:        at CoreArena-3.2.5.jar//org.mineacademy.corearena.lib.fo.settings.SimpleLocalization.onLoad(SimpleLocalization.java:46)
[13:21:06 WARN]:        at CoreArena-3.2.5.jar//org.mineacademy.corearena.lib.fo.settings.YamlStaticConfig.load(YamlStaticConfig.java:88)
[13:21:06 WARN]:        at CoreArena-3.2.5.jar//org.mineacademy.corearena.lib.fo.plugin.AutoRegisterScanner.registerSettings(AutoRegisterScanner.java:175)
[13:21:06 WARN]:        at CoreArena-3.2.5.jar//org.mineacademy.corearena.lib.fo.plugin.AutoRegisterScanner.scanAndRegister(AutoRegisterScanner.java:82)
[13:21:06 WARN]:        at CoreArena-3.2.5.jar//org.mineacademy.corearena.lib.fo.plugin.SimplePlugin.reload(SimplePlugin.java:823)
[13:21:06 WARN]:        at CoreArena-3.2.5.jar//org.mineacademy.corearena.lib.fo.command.ReloadCommand.onCommand(ReloadCommand.java:66)
[13:21:06 WARN]:        at CoreArena-3.2.5.jar//org.mineacademy.corearena.lib.fo.command.SimpleCommand.execute(SimpleCommand.java:393)
[13:21:06 WARN]:        at CoreArena-3.2.5.jar//org.mineacademy.corearena.lib.fo.command.SimpleCommandGroup$MainCommand.onCommand(SimpleCommandGroup.java:444)
[13:21:06 WARN]:        at CoreArena-3.2.5.jar//org.mineacademy.corearena.lib.fo.command.SimpleCommand.execute(SimpleCommand.java:393)
[13:21:06 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[13:21:06 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:906)
[13:21:06 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchServerCommand(CraftServer.java:869)
[13:21:06 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.be(DedicatedServer.java:510)
[13:21:06 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:484)
[13:21:06 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1455)
[13:21:06 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1225)
[13:21:06 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315)
[13:21:06 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by ElBananaa** [comment]
Hey, please replace the content of your localization file with [this one](https://paste.gg/p/anonymous/8c18982098d146e49be7475dae710517), it'll solve your issue. 

It was caused by the plugin trying to call `Commands.Find.Wrong_Syntax` however for some reason, it was actually `Commands.Finds.Wrong_Syntax`.
@kangarko You should update the spanish localization file ^^.
