### ISSUE TITLE
Paper 1.18.2: NoClassDefFoundError

### ISSUE THREAD

**Issue by Jerry-JR** [kangarko/CoreArena#468]
Paper 1.18.2
CoreArena 3.2.6
MythicMobs 5.0.3

While at Spawn Mob

`[23:57:18 ERROR]: CoreArena 3.2.6 encountered a NoClassDefFoundError! Please check your error.log and report this issue with the information in that file.
[23:57:18 INFO]: java.lang.NoClassDefFoundError: io/lumine/mythic/utils/serialize/Position
[23:57:18 INFO]: at CoreArena-3.2.6.jar//org.mineacademy.game.hook.MythicMobsHook.tryMythicalSpawn(CoreHookManager.java:70)
[23:57:18 INFO]: at CoreArena-3.2.6.jar//org.mineacademy.game.hook.CoreHookManager.tryMythicalSpawn(CoreHookManager.java:39)
[23:57:18 INFO]: at CoreArena-3.2.6.jar//org.mineacademy.game.impl.SimplePhaseIncremental.spawnMobs(SimplePhaseIncremental.java:461)
[23:57:18 INFO]: at CoreArena-3.2.6.jar//org.mineacademy.game.impl.SimplePhaseIncremental.startTimer(SimplePhaseIncremental.java:552)
[23:57:18 INFO]: at CoreArena-3.2.6.jar//org.mineacademy.game.impl.arena.SimpleArena.doStart(SimpleArena.java:382)
[23:57:18 INFO]: at CoreArena-3.2.6.jar//org.mineacademy.game.impl.arena.SimpleArena.startArena(SimpleArena.java:319)
[23:57:18 INFO]: at CoreArena-3.2.6.jar//org.mineacademy.game.command.StartCommand.onCommand(StartCommand.java:56)
[23:57:18 INFO]: at CoreArena-3.2.6.jar//org.mineacademy.corearena.lib.command.SimpleCommand.execute(SimpleCommand.java:399)
[23:57:18 INFO]: at CoreArena-3.2.6.jar//org.mineacademy.corearena.lib.command.SimpleCommandGroup$MainCommand.onCommand(SimpleCommandGroup.java:444)
[23:57:18 INFO]: at CoreArena-3.2.6.jar//org.mineacademy.corearena.lib.command.SimpleCommand.execute(SimpleCommand.java:399)
[23:57:18 INFO]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[23:57:18 INFO]: java.lang.ClassNotFoundException: io.lumine.mythic.utils.serialize.Position
[23:57:18 INFO]: at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:151)
[23:57:18 INFO]: at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103)
[23:57:18 INFO]: at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[23:57:18 INFO]: at CoreArena-3.2.6.jar//org.mineacademy.game.hook.MythicMobsHook.tryMythicalSpawn(CoreHookManager.java:70)
[23:57:18 INFO]: at CoreArena-3.2.6.jar//org.mineacademy.game.hook.CoreHookManager.tryMythicalSpawn(CoreHookManager.java:39)
[23:57:18 INFO]: at CoreArena-3.2.6.jar//org.mineacademy.game.impl.SimplePhaseIncremental.spawnMobs(SimplePhaseIncremental.java:461)
[23:57:18 INFO]: at CoreArena-3.2.6.jar//org.mineacademy.game.impl.SimplePhaseIncremental.startTimer(SimplePhaseIncremental.java:552)
[23:57:18 INFO]: at CoreArena-3.2.6.jar//org.mineacademy.game.impl.arena.SimpleArena.doStart(SimpleArena.java:382)
[23:57:18 INFO]: at CoreArena-3.2.6.jar//org.mineacademy.game.impl.arena.SimpleArena.startArena(SimpleArena.java:319)
[23:57:18 INFO]: at CoreArena-3.2.6.jar//org.mineacademy.game.command.StartCommand.onCommand(StartCommand.java:56)
[23:57:18 INFO]: at CoreArena-3.2.6.jar//org.mineacademy.corearena.lib.command.SimpleCommand.execute(SimpleCommand.java:399)
[23:57:18 INFO]: at CoreArena-3.2.6.jar//org.mineacademy.corearena.lib.command.SimpleCommandGroup$MainCommand.onCommand(SimpleCommandGroup.java:444)
[23:57:18 INFO]: at CoreArena-3.2.6.jar//org.mineacademy.corearena.lib.command.SimpleCommand.execute(SimpleCommand.java:399)
[23:57:18 INFO]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)`

**Comment by kangarko** [comment]
Thanks, will be fixed!
