### ISSUE TITLE
1.19: Error message on server shutdown (java.lang.NoClassDefFoundError: github/scarsz/discordsrv/dependencies/jda/api/exceptions/ErrorResponseException)

### ISSUE THREAD

**Issue by PsychoLynx** [kangarko/CoreArena#471]
**What is your current situation, the desired situation, and your problem?**
This is a minor bug, but I thought I would report it anyway. While shutting down the server, CoreArena gives the following error message.

```
[Server thread/ERROR]: Error occurred while disabling CoreArena v3.2.7 (Is it up to date?)
java.lang.NoClassDefFoundError: github/scarsz/discordsrv/dependencies/jda/api/exceptions/ErrorResponseException
	at org.mineacademy.corearena.lib.plugin.SimplePlugin.unregisterReloadables(SimplePlugin.java:859) ~[CoreArena-3.2.5.jar:?]
	at org.mineacademy.corearena.lib.plugin.SimplePlugin.onDisable(SimplePlugin.java:701) ~[CoreArena-3.2.5.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:401) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:573) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:550) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.disablePlugins(CraftServer.java:488) ~[purpur-1.19.jar:git-Purpur-1668]
	at net.minecraft.server.MinecraftServer.stopServer(MinecraftServer.java:942) ~[purpur-1.19.jar:git-Purpur-1668]
	at net.minecraft.server.dedicated.DedicatedServer.stopServer(DedicatedServer.java:820) ~[purpur-1.19.jar:git-Purpur-1668]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1256) ~[purpur-1.19.jar:git-Purpur-1668]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:307) ~[purpur-1.19.jar:git-Purpur-1668]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: github.scarsz.discordsrv.dependencies.jda.api.exceptions.ErrorResponseException
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:153) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:105) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	... 12 more
```

Even though I doubt it matters, I would like to not have plugins erroring on shutdown. I am hoping this is an easy fix!

**Comment by kangarko** [comment]
Thanks, should be resolved in the next version. Also update your Discord SRV.

**Comment by PsychoLynx** [comment]
Thank you very much, will do!
