### ISSUE TITLE
1.19: Truncated class file

### ISSUE THREAD

**Issue by TonyMontero** [kangarko/CoreArena#475]
I don't know how, but I can't make this plugin work.

```
[02:35:36 ERROR]: Fatal error trying to convert CoreArena v3.2.8:skz15/util/HotSwapper$1.class
java.lang.ArrayIndexOutOfBoundsException: null
[02:35:36 INFO]: java.lang.ClassFormatError: Truncated class file
[02:35:36 INFO]: at java.base/java.lang.ClassLoader.defineClass1(Native Method)
[02:35:36 INFO]: at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
[02:35:36 INFO]: at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
[02:35:36 INFO]: at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:200)
[02:35:36 INFO]: at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
[02:35:36 INFO]: at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:110)
[02:35:36 INFO]: at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:105)
[02:35:36 INFO]: at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[02:35:36 INFO]: at CoreArena-3.2.8.jar//org.mineacademy.corearena.lib.plugin.AutoRegisterScanner.findValidClasses(AutoRegisterScanner.java:390)
[02:35:36 INFO]: at CoreArena-3.2.8.jar//org.mineacademy.corearena.lib.plugin.AutoRegisterScanner.scanAndRegister(AutoRegisterScanner.java:79)
[02:35:36 INFO]: at CoreArena-3.2.8.jar//org.mineacademy.corearena.lib.plugin.SimplePlugin.onEnable(SimplePlugin.java:325)
[02:35:36 INFO]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[02:35:36 INFO]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[02:35:36 INFO]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542)
[02:35:36 INFO]:     ___                  _
[02:35:36 INFO]:    / _ \  ___  _ __  ___| |
[02:35:36 INFO]:   | | | |/ _ \| '_ \/ __| |
[02:35:36 INFO]:   | |_| | (_) | |_) \__ \_|
[02:35:36 INFO]:    \___/ \___/| .__/|___(_)
[02:35:36 INFO]:              |_|
[02:35:36 INFO]: !-----------------------------------------------------!
[02:35:36 INFO]: Error loading CoreArena v3.2.8, plugin is disabled!
[02:35:36 INFO]: Running on 1.19-R0.1-SNAPSHOT (v1_19_R1) & Java 17.0.2
[02:35:36 INFO]: !-----------------------------------------------------!
[02:35:36 INFO]: Error: Truncated class file
[02:35:36 INFO]: !-----------------------------------------------------!
```

Using 1.19 (Purpur latest 1.19 build, not 1.19.1)
Using latest CoreArena version

**Comment by kangarko** [comment]
I will reupload, sorry for this.
