### ISSUE TITLE
1.19: Truncated class file (again)

### ISSUE THREAD

**Issue by TonyMontero** [kangarko/CoreArena#476]
**Issue**: I can't enable the plugin, maybe due a plugin incompatibility between him and TerraformGenerator (I don't know when it needs to take classes from that plugin)
**Version**: Latest CoreArena (3.2.10)
**Version**: 1.19 (Purpur)

```
[13:51:48 INFO]: [CoreArena] Enabling CoreArena v3.2.10
[13:51:48 INFO]:     ___                 _
[13:51:48 INFO]:    / __\___  _ __ ___  /_\  _ __ ___ _ __   __ _
[13:51:48 INFO]:   / /  / _ \| '__/ _ \//_\\| '__/ _ \ '_ \ / _` |
[13:51:48 INFO]:  / /__| (_) | | |  __/  _  \ | |  __/ | | | (_| |
[13:51:48 INFO]:  \____/\___/|_|  \___\_/ \_/_|  \___|_| |_|\__,_|
[13:51:48 INFO]:                                             3.2.10
[13:51:48 WARN]: [CoreArena] Loaded class dev.lone.itemsadder.api.FontImages.FontImageWrapper from ItemsAdder v3.2.3e-2 which is not a depend or softdepend of this plugin.
[13:51:48 INFO]: [PlaceholderAPI] Successfully registered expansion: corearena [3.2.10]
[13:51:48 WARN]: [CoreArena] Loaded class net.citizensnpcs.api.trait.Trait from Citizens v2.0.30-SNAPSHOT (build 2606) which is not a depend or softdepend of this plugin.
[13:51:48 WARN]: [CoreArena] Loaded class skz15.ClassPool from TerraformGenerator v8.1.0 which is not a depend or softdepend of this plugin.
[13:51:48 ERROR]: Fatal error trying to convert TerraformGenerator v8.1.0:skz15/util/HotSwapper$1.class
java.lang.ArrayIndexOutOfBoundsException: null
[13:51:48 INFO]: java.lang.ClassFormatError: Truncated class file
[13:51:48 INFO]: at java.base/java.lang.ClassLoader.defineClass1(Native Method)
[13:51:48 INFO]: at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
[13:51:48 INFO]: at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
[13:51:48 INFO]: at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:200)
[13:51:48 INFO]: at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
[13:51:48 INFO]: at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:110)
[13:51:48 INFO]: at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:235)
[13:51:48 INFO]: at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:128)
[13:51:48 INFO]: at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:105)
[13:51:48 INFO]: at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[13:51:48 INFO]: at CoreArena-3.2.10.jar//org.mineacademy.corearena.lib.plugin.AutoRegisterScanner.findValidClasses(AutoRegisterScanner.java:404)
[13:51:48 INFO]: at CoreArena-3.2.10.jar//org.mineacademy.corearena.lib.plugin.AutoRegisterScanner.scanAndRegister(AutoRegisterScanner.java:79)
[13:51:48 INFO]: at CoreArena-3.2.10.jar//org.mineacademy.corearena.lib.plugin.SimplePlugin.onEnable(SimplePlugin.java:325)
[13:51:48 INFO]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[13:51:48 INFO]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[13:51:48 INFO]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542)
[13:51:48 INFO]:     ___                  _
[13:51:48 INFO]:    / _ \  ___  _ __  ___| |
[13:51:48 INFO]:   | | | |/ _ \| '_ \/ __| |
[13:51:48 INFO]:   | |_| | (_) | |_) \__ \_|
[13:51:48 INFO]:    \___/ \___/| .__/|___(_)
[13:51:48 INFO]:              |_|
[13:51:48 INFO]: !-----------------------------------------------------!
[13:51:48 INFO]: Error loading CoreArena v3.2.10, plugin is disabled!
[13:51:48 INFO]: Running on 1.19-R0.1-SNAPSHOT (v1_19_R1) & Java 17.0.2
[13:51:48 INFO]: !-----------------------------------------------------!
[13:51:48 INFO]: Error: Truncated class file
[13:51:48 INFO]: !-----------------------------------------------------!
[13:51:48 INFO]: [CoreArena] Disabling CoreArena v3.2.10
```

**Comment by kangarko** [comment]
Your TerraformGenerator is broken most likely, you need to redownload it.

We scan all plugin's classes to hook into supported plugins, I will try to ignore this error completely in the next version at your own risk.
