### ISSUE TITLE
1.18.2: org.mineacademy.corearena.lib.exception.FoException

### ISSUE THREAD

**Issue by Experimentali** [kangarko/CoreArena#495]
[01:02:02 ERROR]: CoreArena 3.5.0 encountered a FoException! Please check your error.log and report this issue with the information in that file. Running Pufferfish 1.18.2-R0.1-SNAPSHOT and Java 17.0.7
[01:02:02 INFO]: org.mineacademy.corearena.lib.exception.FoException: Report: Report / There is no spawnpoint at arenaWorld [40, 80, 84]
[01:02:02 INFO]:        at CoreArena-3.5.0.jar//org.mineacademy.corearena.lib.Valid.checkNotNull(Valid.java:59)
[01:02:02 INFO]:        at CoreArena-3.5.0.jar//org.mineacademy.game.impl.SimpleData.removeSpawnPoint(SimpleData.java:295)
[01:02:02 INFO]:        at CoreArena-3.5.0.jar//org.mineacademy.game.tool.SpawnSelectorMonster.handleBlockBreak(SpawnSelectorMonster.java:53)
[01:02:02 INFO]:        at CoreArena-3.5.0.jar//org.mineacademy.game.visualize.ToolVisualizer.onRemove(ToolVisualizer.java:128)
[01:02:02 INFO]:        at CoreArena-3.5.0.jar//org.mineacademy.game.visualize.ToolVisualizer.onBlockClick(ToolVisualizer.java:120)
[01:02:02 INFO]:        at CoreArena-3.5.0.jar//org.mineacademy.corearena.lib.menu.tool.ToolsListener.onToolClick(ToolsListener.java:81)
[01:02:02 INFO]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor840.execute(Unknown Source)
[01:02:02 INFO]:        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75)
[01:02:02 INFO]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
[01:02:02 INFO]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[01:02:02 INFO]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:671)
[01:02:02 INFO]: [CoreArena] !-----------------------------------------------------!
[01:02:02 INFO]: [CoreArena]  Failed to handle LEFT_CLICK_BLOCK using tool: class org.mineacademy.game.tool.SpawnSelectorMonster
[01:02:02 INFO]: [CoreArena] !-----------------------------------------------------!

**Comment by Experimentali** [comment]
Ok so it looks like it's happening when you click on a block with gravity with the mobspawn clone.
