### ISSUE TITLE
1.21: Tool broke again 

### ISSUE THREAD

**Issue by Rexmen1** [kangarko/CoreArena#517]
[04:40:09 INFO]: [CoreArena] !-----------------------------------------------------!
[04:40:09 INFO]: [CoreArena]  Failed to handle LEFT_CLICK_BLOCK using tool: class org.mineacademy.game.tool.CloneSpawnerToolOn
[04:40:09 INFO]: [CoreArena] !-----------------------------------------------------!
[04:40:10 ERROR]: CoreArena 3.9.2 encountered a FoException! Please check your error.log and report this issue with the information in that file. Running Paper 1.21-R0.1-SNAPSHOT and Java 21.0.3
[04:40:10 INFO]: org.mineacademy.corearena.lib.exception.FoException: Report: Clone Tool for rexmen is ON but lacks a spawner point
[04:40:10 INFO]:        at CoreArena-3.9.2.jar//org.mineacademy.corearena.lib.Valid.checkNotNull(Valid.java:60)
[04:40:10 INFO]:        at CoreArena-3.9.2.jar//org.mineacademy.game.tool.CloneSpawnerToolOn.onBlockClick(CloneSpawnerToolOn.java:63)
[04:40:10 INFO]:        at CoreArena-3.9.2.jar//org.mineacademy.corearena.lib.menu.tool.ToolsListener.onToolClick(ToolsListener.java:82)
[04:40:10 INFO]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1907.execute(Unknown Source)
[04:40:10 INFO]:        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
[04:40:10 INFO]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77)
[04:40:10 INFO]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[04:40:10 INFO]:        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[04:40:10 INFO]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131)
[04:40:10 INFO]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628)
[04:40:10 INFO]: [CoreArena] !-----------------------------------------------------!
[04:40:10 INFO]: [CoreArena]  Failed to handle RIGHT_CLICK_BLOCK using tool: class org.mineacademy.game.tool.CloneSpawnerToolOn
[04:40:10 INFO]: [CoreArena] !-----------------------------------------------------!

**Comment by Rexmen1** [comment]
also saving swords in here is broken? https://gyazo.com/30b8af605a356931b674bda4e11fb61c

**Comment by kangarko** [comment]
Thanks, will fix both issues tonight.
