### ISSUE TITLE
Update to 1.21.1 Minecraft version 1.21.1 #39

### ISSUE THREAD

**Issue by cobrex1** [kangarko/CoreArena#532]
The plugin disables on load.

I am aware you are updating plugins for 1.21.1 as seen the new Boss version.

Here is the error message for your reference:

[19:57:12] [Server thread/INFO]: java.lang.ExceptionInInitializerError
[19:57:12] [Server thread/INFO]: 	at CoreArena-3.9.6.jar//org.mineacademy.corearena.lib.remain.nbt.NBTCompound.setString(NBTCompound.java:157)
[19:57:12] [Server thread/INFO]: 	at CoreArena-3.9.6.jar//org.mineacademy.corearena.lib.remain.CompMetadata.lambda$setMetadata$0(CompMetadata.java:97)
[19:57:12] [Server thread/INFO]: 	at CoreArena-3.9.6.jar//org.mineacademy.corearena.lib.remain.nbt.NBT.modify(NBT.java:171)
[19:57:12] [Server thread/INFO]: 	at CoreArena-3.9.6.jar//org.mineacademy.corearena.lib.remain.CompMetadata.setMetadata(CompMetadata.java:92)
[19:57:12] [Server thread/INFO]: 	at CoreArena-3.9.6.jar//org.mineacademy.corearena.lib.menu.model.ItemCreator.make(ItemCreator.java:812)
[19:57:12] [Server thread/INFO]: 	at CoreArena-3.9.6.jar//org.mineacademy.game.visualize.ToolVisualizer.getItem(ToolVisualizer.java:182)
[19:57:12] [Server thread/INFO]: 	at CoreArena-3.9.6.jar//org.mineacademy.game.tool.LobbySelector.getTool(LobbySelector.java:23)
[19:57:12] [Server thread/INFO]: 	at CoreArena-3.9.6.jar//org.mineacademy.game.menu.MenuGameTools.compileTools(MenuGameTools.java:24)
[19:57:12] [Server thread/INFO]: 	at CoreArena-3.9.6.jar//org.mineacademy.corearena.lib.menu.MenuTools.<init>(MenuTools.java:48)
[19:57:12] [Server thread/INFO]: 	at CoreArena-3.9.6.jar//org.mineacademy.corearena.lib.menu.MenuTools.<init>(MenuTools.java:37)
[19:57:12] [Server thread/INFO]: 	at CoreArena-3.9.6.jar//org.mineacademy.game.menu.MenuGameTools.<init>(MenuGameTools.java:18)
[19:57:12] [Server thread/INFO]: 	at CoreArena-3.9.6.jar//org.mineacademy.game.menu.MenuGameTools.<clinit>(MenuGameTools.java:16)
[19:57:12] [Server thread/INFO]: 	at CoreArena-3.9.6.jar//org.mineacademy.corearena.CoreArenaPlugin.onPluginStart(CoreArenaPlugin.java:133)
[19:57:12] [Server thread/INFO]: 	at CoreArena-3.9.6.jar//org.mineacademy.corearena.lib.plugin.SimplePlugin.onEnable(SimplePlugin.java:321)
[19:57:12] [Server thread/INFO]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288)
[19:57:12] [Server thread/INFO]: 	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
[19:57:12] [Server thread/INFO]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
[19:57:12] [Server thread/INFO]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
[19:57:12] [Server thread/INFO]: java.lang.NullPointerException: Cannot invoke "Object.hashCode()" because "pk" is null
[19:57:12] [Server thread/INFO]: 	at java.base/java.util.ImmutableCollections$MapN.probe(ImmutableCollections.java:1328)
[19:57:12] [Server thread/INFO]: 	at java.base/java.util.ImmutableCollections$MapN.get(ImmutableCollections.java:1242)
[19:57:12] [Server thread/INFO]: 	at java.base/java.util.ImmutableCollections$AbstractImmutableMap.getOrDefault(ImmutableCollections.java:1097)
[19:57:12] [Server thread/INFO]: 	at io.papermc.paper.pluginremap.reflect.PaperReflection.mapDeclaredFieldName(PaperReflection.java:79)
[19:57:12] [Server thread/INFO]: 	at io.papermc.reflectionrewriter.runtime.AbstractDefaultRulesReflectionProxy.getDeclaredField(AbstractDefaultRulesReflectionProxy.java:90)
[19:57:12] [Server thread/INFO]: 	at io.papermc.paper.pluginremap.reflect.PaperReflectionHolder.getDeclaredField(Unknown Source)
[19:57:12] [Server thread/INFO]: 	at CoreArena-3.9.6.jar//org.mineacademy.corearena.lib.remain.nbt.NBTReflectionUtil.<clinit>(NBTReflectionUtil.java:50)
[19:57:12] [Server thread/INFO]: 	at CoreArena-3.9.6.jar//org.mineacademy.corearena.lib.remain.nbt.NBTCompound.setString(NBTCompound.java:157)
[19:57:12] [Server thread/INFO]: 	at CoreArena-3.9.6.jar//org.mineacademy.corearena.lib.remain.CompMetadata.lambda$setMetadata$0(CompMetadata.java:97)
[19:57:12] [Server thread/INFO]: 	at CoreArena-3.9.6.jar//org.mineacademy.corearena.lib.remain.nbt.NBT.modify(NBT.java:171)
[19:57:12] [Server thread/INFO]: 	at CoreArena-3.9.6.jar//org.mineacademy.corearena.lib.remain.CompMetadata.setMetadata(CompMetadata.java:92)
[19:57:12] [Server thread/INFO]: 	at CoreArena-3.9.6.jar//org.mineacademy.corearena.lib.menu.model.ItemCreator.make(ItemCreator.java:812)
[19:57:12] [Server thread/INFO]: 	at CoreArena-3.9.6.jar//org.mineacademy.game.visualize.ToolVisualizer.getItem(ToolVisualizer.java:182)
[19:57:12] [Server thread/INFO]: 	at CoreArena-3.9.6.jar//org.mineacademy.game.tool.LobbySelector.getTool(LobbySelector.java:23)
[19:57:12] [Server thread/INFO]: 	at CoreArena-3.9.6.jar//org.mineacademy.game.menu.MenuGameTools.compileTools(MenuGameTools.java:24)
[19:57:12] [Server thread/INFO]: 	at CoreArena-3.9.6.jar//org.mineacademy.corearena.lib.menu.MenuTools.<init>(MenuTools.java:48)
[19:57:12] [Server thread/INFO]: 	at CoreArena-3.9.6.jar//org.mineacademy.corearena.lib.menu.MenuTools.<init>(MenuTools.java:37)
[19:57:12] [Server thread/INFO]: 	at CoreArena-3.9.6.jar//org.mineacademy.game.menu.MenuGameTools.<init>(MenuGameTools.java:18)
[19:57:12] [Server thread/INFO]: 	at CoreArena-3.9.6.jar//org.mineacademy.game.menu.MenuGameTools.<clinit>(MenuGameTools.java:16)
[19:57:12] [Server thread/INFO]: 	at CoreArena-3.9.6.jar//org.mineacademy.corearena.CoreArenaPlugin.onPluginStart(CoreArenaPlugin.java:133)
[19:57:12] [Server thread/INFO]: 	at CoreArena-3.9.6.jar//org.mineacademy.corearena.lib.plugin.SimplePlugin.onEnable(SimplePlugin.java:321)
[19:57:12] [Server thread/INFO]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288)
[19:57:12] [Server thread/INFO]: 	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
[19:57:12] [Server thread/INFO]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
[19:57:12] [Server thread/INFO]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
[19:57:12] [Server thread/INFO]:     ___                  _ 
[19:57:12] [Server thread/INFO]:    / _ \  ___  _ __  ___| |
[19:57:12] [Server thread/INFO]:   | | | |/ _ \| '_ \/ __| |
[19:57:12] [Server thread/INFO]:   | |_| | (_) | |_) \__ \_|
[19:57:12] [Server thread/INFO]:    \___/ \___/| .__/|___(_)
[19:57:12] [Server thread/INFO]:              |_|          
[19:57:12] [Server thread/INFO]: !-----------------------------------------------------!
[19:57:12] [Server thread/INFO]:  Error loading CoreArena v3.9.6, plugin is disabled!
[19:57:12] [Server thread/INFO]:  Running on 1.21.1-R0.1-SNAPSHOT & Java 21.0.3
[19:57:12] [Server thread/INFO]: !-----------------------------------------------------!
[19:57:12] [Server thread/INFO]:  Error: Cannot invoke "Object.hashCode()" because "pk" is null
[19:57:12] [Server thread/INFO]: !-----------------------------------------------------!
[19:57:12] [Server thread/INFO]: [CoreArena] Disabling CoreArena v3.9.6

**Comment by kangarko** [comment]
I am aware, but not a priority, wanted to update the most popular plugins as soon as possible, others must wait unfortunately

**Comment by kangarko** [comment]
Thanks, we all look forward to update. I did not expect it to take over a month. You can track foundation progress at https://github.com/kangarko/Foundation/commits/v7/

**Comment by kangarko** [comment]
@cobrex1 I pushed an emergency update so you don't need to wait :)
