### ISSUE TITLE
Exit and enter dungeons while eating golden apples Each turn like that has +20 max health and spam the console

### ISSUE THREAD

**Issue by tuanhp0** [kangarko/CoreArena#539]
![image (1)](https://github.com/user-attachments/assets/d4ec28b1-510b-445a-b813-3e3e7a5cbe5c)

[14:53:18] [User Authenticator #91/INFO]: UUID of player ydeptraiso1 is e
[14:53:19] [Server thread/INFO]: Thestalo issued server command: /warps
[14:53:19] [Server thread/INFO]: Hirita issued server command: /shop
[14:53:19] [Server thread/INFO]: ydeptraiso1[] logged in with entity id 519101 at ([AztecDungeons]2095.014590428246, 149.0, 2027.3774471152774)
[14:53:19] [Server thread/INFO]: [+] ydeptraiso1
[14:53:19] [Server thread/WARN]: java.lang.IllegalArgumentException: Health value (210.0) must be between 0 and 44.0. (attribute base value: 44.0, player: ydeptraiso1)
[14:53:19] [Server thread/WARN]: 	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:482)
[14:53:19] [Server thread/WARN]: 	at org.bukkit.craftbukkit.entity.CraftLivingEntity.setHealth(CraftLivingEntity.java:107)
[14:53:19] [Server thread/WARN]: 	at CoreArena-4.0.3 (1).jar//org.mineacademy.corearena.util.StoredInventory.restore(InventoryStorageUtil.java:175)
[14:53:19] [Server thread/WARN]: 	at CoreArena-4.0.3 (1).jar//org.mineacademy.corearena.util.StoredInventory.restoreIfStored(InventoryStorageUtil.java:151)
[14:53:19] [Server thread/WARN]: 	at CoreArena-4.0.3 (1).jar//org.mineacademy.corearena.util.InventoryStorageUtil.restoreIfStored(InventoryStorageUtil.java:85)
[14:53:19] [Server thread/WARN]: 	at CoreArena-4.0.3 (1).jar//org.mineacademy.corearena.listener.PlayerListener.lambda$onJoin$1(PlayerListener.java:57)
[14:53:19] [Server thread/WARN]: 	at CoreArena-4.0.3 (1).jar//org.mineacademy.corearena.lib.remain.Remain$1.run(Remain.java:3011)
[14:53:19] [Server thread/WARN]: 	at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86)
[14:53:19] [Server thread/WARN]: 	at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:475)
[14:53:19] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1748)
[14:53:19] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:483)
[14:53:19] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1620)
[14:53:19] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1320)
[14:53:19] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:334)
[14:53:19] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by tuanhp0** [comment]
my server 1.21.1 - Corearena 4.0.4 (dowload new BBB 4.0.3)

**Comment by kangarko** [comment]
Let me get back to you in 24 hours

**Comment by kangarko** [comment]
Sorry unfortunately I had to delay it, but I should be finally sitting down this weekend.

**Comment by kangarko** [comment]
Thanks, fixed. Will release the plugin tonight, thank you for your patience!
