### ISSUE TITLE
Issue running mvtp on Player_Leave

### ISSUE THREAD

**Issue by bc-hill** [kangarko/CoreArena#54]
I need players to teleport to another world after they leave the arena, ideally after their inventories are restored.  
Other arena plugins have an exit point, where the player warps to after the game is completely over.  Even if the other plugin cannot support mvtp, I can set the exit point to be right above a pressure plate, which then triggers mvtp.  This works surprisingly well.

Anyway, in the arena file I set this:
>   Player_Leave: 
    Player: []
    Console:
      - "/mvtp {player} e:ServerSpawn:-1538,108,707:0:0"

But then I am returned to the arena world immediately, and console says:
> [18:02:41] [Server thread/INFO]: player_name issued server command: /ma leave
[18:02:41] [Server thread/INFO]: Arena // CoreArena 1.5.3 encountered a IllegalArgumentException! Please check your error.log and report this issue with the information in that file.
[18:02:41] [Server thread/INFO]: java.lang.IllegalArgumentException: Cannot measure distance between ServerSpawn and corearena_small-rustic-pvp
[18:02:41] [Server thread/INFO]: 	at org.bukkit.Location.distanceSquared(Location.java:460)
[18:02:41] [Server thread/INFO]: 	at org.bukkit.Location.distance(Location.java:443)
[18:02:41] [Server thread/INFO]: 	at me.kangarko.corearena.nul. .cOm3.nul(SourceFile:597)
[18:02:41] [Server thread/INFO]: 	at me.kangarko.corearena.nul. .cOm3.nul(SourceFile:532)
[18:02:41] [Server thread/INFO]: 	at me.kangarko.corearena.nul. .cOm3.kickPlayer(SourceFile:490)
[18:02:41] [Server thread/INFO]: 	at me.kangarko.corearena.nul. .CoM3.handleSubCommand(SourceFile:26)
[18:02:41] [Server thread/INFO]: 	at me.kangarko.corearena.kautils.command.Lpt5.handleCommand(SourceFile:182)
[18:02:41] [Server thread/INFO]: 	at me.kangarko.corearena.kautils.command.BaseCommand.onCommand(SourceFile:53)
[18:02:41] [Server thread/INFO]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[18:02:41] [Server thread/INFO]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[18:02:41] [Server thread/INFO]: Arena // *-----------------------------------------------*
[18:02:41] [Server thread/INFO]: Arena //  Error while removing player player_name from small-rustic-pvp
[18:02:41] [Server thread/INFO]: Arena //  Moving him to spawn.
[18:02:41] [Server thread/INFO]: Arena //  IllegalArgumentException: Cannot measure distance between ServerSpawn and corearena_small-rustic-pvp
[18:02:41] [Server thread/INFO]: Arena // *-----------------------------------------------*
[18:02:41] [Server thread/INFO]: Arena // GG! The game in small-rustic-pvp has finished!

Edit: The issue appears to be that Player_Leave triggers before CoreArena is completely finished ending the game.
Maybe you could just add commands that run after the plugin finishes?

**Comment by bc-hill** [comment]
>------------------------------------[ 17.02.2018 18:44:52 ]-----------------------------------
CoreArena 1.5.3 encountered a IllegalArgumentException
Running CraftBukkit 1.12.2-R0.1-SNAPSHOT and Java 1.8.0_144
Plugins: CoreProtect v2.14.2, LuckPerms v4.0.80, WorldEdit v6.1.8-SNAPSHOT;cd4729f, CityWorld v3.02, PlaceholderAPI v2.8.2, Vehicles v9.2.1, Craftconomy3 v3.3.1-d99cf63-trv200, Boss v1.5.10, WorldBorder v1.8.7, DecoHeads v1.4, RelaJumpPads v1.0, WorldGuard v6.2.1;84bc322, The Multiverse-Core Plugin, AdvancedPortals v0.0.38, GameAPI v1.1.1, VoidGenerator v1.2.0, CraftDisplay v5.0.2, SimpleAPI v3.8, Vault v1.5.6-b49, statuecreator v1.5, Sit v1.0, Essentials v2.0.1-b594, ArmorStandTools v2.4.3, ChatControl v7.6.34, PerWorldInventory v1.11.5, HolographicDisplays v2.2.6, LWC v1.9.4, CommandSigns v1.6.4, SimplePets v3.9, Citizens v2.0.22-SNAPSHOT (build 1497), BlockBall v4.1.1, MythicMobs v4.3.2-SNAPSHOT, HeavySpleef v2.4.1-b341, MCPainter v2.0.0-dev, WanderingNPC v1.7, CraftBook v3.9-SNAPSHOT-jenkins-CraftBook-203, CoreArena v1.5.3, Sentinel v1.4.5 (build 157)
----------------------------------------------------------------------------------------------

>More Information: 
Error while removing player player_name from small-rustic-pvp
Moving him to spawn.
%error
IllegalArgumentException Cannot measure distance between ServerSpawn and corearena_small-rustic-pvp
	 at org.bukkit.Location.distanceSquared(Location.java:460)
	 at org.bukkit.Location.distance(Location.java:443)
	 at me.kangarko.corearena.nul. .cOm3.nul(SourceFile:597)
	 at me.kangarko.corearena.nul. .cOm3.nul(SourceFile:532)
	 at me.kangarko.corearena.nul. .cOm3.kickPlayer(SourceFile:490)
	 at me.kangarko.corearena.nul. .CoM3.handleSubCommand(SourceFile:26)
	 at me.kangarko.corearena.kautils.command.Lpt5.handleCommand(SourceFile:182)
	 at me.kangarko.corearena.kautils.command.BaseCommand.onCommand(SourceFile:53)
	 at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
	 at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
	 at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648)
----------------------------------------------------------------------------------------------

**Comment by kangarko** [comment]
[ArenaTeleport.zip](https://github.com/kangarko/CoreArena/files/1747758/ArenaTeleport.zip)

Hey, I am sorry this turned out to be real pain to fix, so I made a small plugin for that (feel free to decompile). You configure that location in that plugin's config.yml.

**Comment by bc-hill** [comment]
Hey, this is a pretty full-featured temp fix plugin!
Seems to work well, using my mvtp command.  So far, no conflicts with PerWorldInventories, like I was worried about.
What impact does the delay-ticks setting have?  Is the plugin triggered by corearena on player_leave, and the delay is to let corearena finish up?
Thank you!

**Comment by kangarko** [comment]
It's actually really small 49 lined plugin (see below). Yes, the delay only postpones the commands that are run after a player left an arena.
![a](https://i.imgur.com/8tYXPkI.png)

The ArenaLeaveEvent is called at the very last when a player leaves.
![b](https://i.imgur.com/OXiu7ol.png)

That leave method is again called at the very last when an arena stops. We also include security kick-out in case of a failure. I don't understand how CA won't finish clean-up since those methods are at the bottom but at present I am working on a more important project.
![c](https://i.imgur.com/yw1ApVQ.png)

**Comment by kangarko** [comment]
I referenced this issue to Wiki and added ArenaTeleport as the official workaround. This turned to be a really hard to fix and that plugin handles it extremely cleanly and well so it will stay that way for the time being.

**Comment by kangarko** [comment]
Here's a new version of ArenaTeleport made for the recent recode.

[ArenaTeleport.zip](https://github.com/kangarko/CoreArena/files/3245901/ArenaTeleport.zip)

**Comment by Eth4ck1e** [comment]
ArenaTeleport will not load, I am getting a gameapi dependency error but I also get an error saying gameapi is no longer needed and to remove it.  Is there a workaround for this issue?

**Comment by LeehamElectronics** [comment]
Just install GameAPI and ignore the messages from CoreArena about being no longer needed, does that work @Eth4ck1e  ?
Thanks

**Comment by Eth4ck1e** [comment]
No, Unfortunately  I should have been more clear, With gameAPI installed corearena disables itself as part of the error message, So I cannot ignore it.

**Comment by kangarko** [comment]
GameAPI has been deleted and you must remove it to use the latest CoreArena.

Now, I have to apology because I am out of workspace and I did not synchronize code for ArenaTeleport. Not sure how long I stay out, maybe a few weeks. I recommend downgrading CoreArena and maybe spending a low $5-15 on a developer that can maintain that plugin for you.

However, since you made this post, we added the option of running commands when arena ends. So you could do something like that in your arena yml file:

<img width="505" alt="Skjermbilde 2020-10-31 kl  18 42 19" src="https://user-images.githubusercontent.com/1918426/97786011-d3fd9880-1ba8-11eb-9021-c9fb5af2ccc8.png">

**Comment by Eth4ck1e** [comment]
Thank you for the help!  I was using tppos command under the console and it worked but was throwing a lot of errors.  using teleport under the player option is proving a much better solution.  No more errors, and players still keep their gear between worlds. :)
