### ISSUE TITLE
Phase 2

### ISSUE THREAD

**Issue by DivisionStalker** [kangarko/CoreArena#59]
More Information: 
Arena Test has failed entering phase: 2
Stopping arena for safety.
%error
NoClassDefFoundError Could not initialize class me.kangarko.corearena.nul. .aD
	 at me.kangarko.corearena.nul. .aE.nul(SourceFile:469)
	 at me.kangarko.corearena.nul. .CoM1.broadcastBar(SourceFile:100)
	 at me.kangarko.corearena.nul. .LPt8.onNextPhase(SourceFile:157)
	 at me.kangarko.corearena.nul. .COm3.IlIlIlllIIllIlIlIlIlIllIIIIIlIlllIlIIlllIlIIIIIllllIIlIIIIIIIllllllIIIlIlIllIlIllllllllIlIllllIlIIIlIIIlllIIlIlIlIIlllllIlllIlllIIllIllIIIlllllIIIlIlIllIllIIlIlllIlIIIllIllIllIllllIIIllIIlIlllllllIIIlIllllIllIlIlIIIllllIlllIllIlllIlIIlIlllIlllIIIIIIlIlIlIlIlIlllllIIlIllllllIIlIlllIlIlIllIllIlIIlIlIIlIIllIlIIlllIIlIIlllllIlIlIllIIlIllllIlllIIIIIllIlIlIllllIIlIllIIlIIIllIIlIlIlIlIlllIllllllIIIllllllIIIIIlIIIIIlIlIIlIllIIIIllIlIIllIIIIlIlIIlIllIIllIlIlIllllIIIIIllIlllIIIIlIIlllIllIlIllIIlllllIlllII(SourceFile:23)
	 at me.kangarko.corearena.nul. .break.run(SourceFile:35)
	 at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:53)
	 at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352)

**Comment by kangarko** [comment]
Have you used PlugMan or /reload when updating the plugin? If so, never use that but, rather shut your server down when updating.

**Comment by DivisionStalker** [comment]
I have buyed the plugin and installed it direktly since i buyed it i think it was no Update Server reastart ist have tryed linke 20 Times and no i dont Use plugman

Gesendet von Yahoo Mail auf Android 
 
  Am Do., März 15, 2018 at 10:57 schrieb kangarko<notifications@github.com>:   
Have you used PlugMan or /reload when updating the plugin? If so, never use that but, rather shut your server down when updating.

**Comment by kangarko** [comment]
Hey, sorry for a late answer. I reviewed the code again, did some testing and came to the following:

Are you using Spigot, Craftbukkit or any other distribution ? Puncher requires Spigot and won't work on only Craftbukkit.

Also, please check your errors.yml file for additional information about that error. Also please post me what the plugin says when your server starts.

**Comment by kangarko** [comment]
Hey, sorry for a late answer. I reviewed the code again, did some testing and came to the following:

Are you using Spigot, Craftbukkit or any other distribution ? CoreArena requires Spigot and won't work on only Craftbukkit.

Also, please check your errors.yml file for additional information about that error. Also please post me what the plugin says when your server starts.

**Comment by kangarko** [comment]
Closing due to inactivity. Please let me know if the issues persist.
