### ISSUE TITLE
Menu class me.kangarko.corearena.nul. .coM5$AUX cannot be refreshed

### ISSUE THREAD

**Issue by mibby** [kangarko/CoreArena#79]
CoreArena v1.6.4
Paper dev 1424 (Spigot 1.12.2)
```
[02:07:04] [Server thread/WARN]: [CoreArena] Plugin CoreArena v1.6.4 generated an exception whilst handling conversation input
me.kangarko.corearena.nul. .k: Report / Menu class me.kangarko.corearena.nul. .coM5$AUX cannot be refreshed
	at me.kangarko.corearena.nul. .class.nul(SourceFile:20) ~[CoreArena-1.6.4.jar:?]
	at me.kangarko.corearena.nul. .auX.conversationAbandoned(SourceFile:32) ~[CoreArena-1.6.4.jar:?]
	at org.bukkit.conversations.Conversation.abandon(Conversation.java:271) ~[patched_1.12.2.jar:git-Paper-1424]
	at org.bukkit.conversations.Conversation.outputNextPrompt(Conversation.java:282) ~[patched_1.12.2.jar:git-Paper-1424]
	at org.bukkit.conversations.Conversation.acceptInput(Conversation.java:229) ~[patched_1.12.2.jar:git-Paper-1424]
	at org.bukkit.craftbukkit.v1_12_R1.conversations.ConversationTracker.acceptConversationInput(ConversationTracker.java:60) [patched_1.12.2.jar:git-Paper-1424]
	at org.bukkit.craftbukkit.v1_12_R1.entity.CraftPlayer.acceptConversationInput(CraftPlayer.java:1300) [patched_1.12.2.jar:git-Paper-1424]
	at net.minecraft.server.v1_12_R1.PlayerConnection$5.evaluate(PlayerConnection.java:1291) [patched_1.12.2.jar:git-Paper-1424]
	at org.bukkit.craftbukkit.v1_12_R1.util.Waitable.run(Waitable.java:24) [patched_1.12.2.jar:git-Paper-1424]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:854) [patched_1.12.2.jar:git-Paper-1424]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427) [patched_1.12.2.jar:git-Paper-1424]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.2.jar:git-Paper-1424]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1424]
	at java.lang.Thread.run(Thread.java:844) [?:?]

```

**Comment by kangarko** [comment]
Should be fixed now. Next time please also include what menu did you open for this error to show up.

**Comment by mibby** [comment]
I didn't open any menus. It just started to output for everyone who logged in after the restart, but thanks for the fix regardless!
